import { gunzipSync } from 'node:zlib';
import { z } from 'zod';
import { sha256, stableJson } from './run-files';
import { EBIRD_SOURCE, EBIRD_ADAPTER, EBIRD_DATASET, EBIRD_LICENSE, qualifyEbirdOriginal, readEbirdArchive, readEbirdPinned, type EbirdFile, type EbirdCounty, type EbirdRecord } from './ebird-original-observations';
import type { SourceAdapterContext, SourceAdapterResult } from './source-adapter';

export const EBIRD_SELECTED_VERSION = '2.0.0';
export const EBIRD_SELECTED_MODE = 'retained-reviewed-selected-ebird-observations';
export const EBIRD_SELECTED_METHOD = 'retained-ebird-selected-original-review-v1';
export const EBIRD_SELECTED_COLLECTIONS = ['EBIRD', 'EBIRD_ATL_NY', 'EBIRD_ATL_NC'] as const;
type Read = (path:string)=>Buffer;
const check:(value:unknown,message:string)=>asserts value=(value,message)=>{if(!value)throw new Error('EOD selected originals: '+message);};
const term=(name:string)=>'http://rs.tdwg.org/dwc/terms/'+name;
const decode=(b:Buffer)=>new TextDecoder('utf-8',{fatal:true}).decode(b);
const hash=z.string().regex(/^[a-f0-9]{64}$/u),commit=z.string().regex(/^[a-f0-9]{40}$/u);
const safePath=z.string().regex(/^[a-zA-Z0-9.][a-zA-Z0-9_./-]+$/u).refine(p=>!p.split('/').includes('..')&&!p.includes('//'));
const file=z.object({path:safePath,bytes:z.number().int().positive().max(20000000),sha256:hash}).strict();
const methodPath=safePath.refine(p=>/^src\/data\/research\/source-method-reviews\/ebird-selected-original-[a-z0-9-]+\.json$/u.test(p));
const pair=z.string().regex(/^\d{5}:[a-z0-9-]+$/u),key=z.number().int().positive();
export const ebirdSelectedParametersSchema=z.object({mode:z.literal(EBIRD_SELECTED_MODE),stateCode:z.string().regex(/^[A-Z]{2}$/u),methodReviewPath:methodPath,methodReviewSha256:hash,candidatePairs:z.array(pair).min(1).max(5000),candidateLimit:z.number().int().positive().max(5000)}).strict();
export type EbirdSelectedPlan=Pick<z.infer<typeof ebirdSelectedParametersSchema>,'methodReviewPath'|'methodReviewSha256'>;
const acquisition=z.object({name:z.enum(['search-initial','search-resume','selected-originals','metadata','context']),archive:file,receipt:file,recipe:file,repositoryBaseCommit:commit.nullable()}).strict();
const collectionContextSchema=z.object({archive:file,receipt:file,recipe:file,repositoryBaseCommit:commit}).strict();
const independent=z.object({actorId:z.string().min(1),baseSha:commit,originalCommit:commit,proposal:file,recipe:file,retention:file}).strict();
export const ebirdSelectedMethodSchema=z.object({schemaVersion:z.literal(1),methodVersion:z.literal(EBIRD_SELECTED_METHOD),sourceId:z.literal(EBIRD_SOURCE),datasetKey:z.literal(EBIRD_DATASET),sourceYear:z.literal(2024),status:z.literal('approved-with-specific-holds'),reviewedBy:z.literal('MAIN'),reviewedAt:z.string().datetime(),acquisitions:z.array(acquisition).length(5),collectionContext:collectionContextSchema,independentReviews:z.array(independent).min(2),taxa:z.record(z.string(),z.object({scientificName:z.string().min(1),taxonKey:key}).strict()),approvedPairs:z.array(pair).min(1),heldPairs:z.array(pair),deferredPairs:z.array(pair),attribution:z.string().min(1),rationale:z.string().min(1),limitations:z.array(z.string().min(1)).min(1)}).strict();
const reviewPair=z.object({pairKey:pair,primaryKey:key.nullable(),recordKeys:z.array(key).min(1),heldKeys:z.array(key),disposition:z.enum(['supported','held'])}).strict();
const adapterReview=z.object({actorId:z.string().min(1),baseSha:commit,status:z.literal('proposal-ready-main-method-required'),pairs:z.array(reviewPair).min(1)}).strict();
const response=file.extend({url:z.url(),status:z.literal(200),retrievedAt:z.string().datetime(),decodedBytes:z.number().int().positive().max(20000000),decodedSha256:hash}).passthrough();
const only=({path,bytes,sha256}:EbirdFile):EbirdFile=>({path,bytes,sha256});
const unique=<T,>(a:T[])=>new Set(a).size===a.length;
const sorted=(a:number[])=>[...a].sort((x,y)=>x-y);
const eq=(a:unknown,b:unknown)=>stableJson(a)===stableJson(b);
type Method=z.infer<typeof ebirdSelectedMethodSchema>;

// This acquisition profile verifies a contiguous retained partial search and a
// separately complete finite selection of original-record GETs. Neither the
// selected set nor a positive record closes the parent search.
export function loadEbirdSelectedSource(method:Pick<Method,'acquisitions'|'collectionContext'|'sourceYear'|'datasetKey'|'taxa'|'reviewedAt'>,read:Read){
  check(method.datasetKey===EBIRD_DATASET&&method.sourceYear===2024,'annual dataset profile differs');
  const definitions=z.array(acquisition).length(5).parse(method.acquisitions);check(unique(definitions.map(a=>a.name)),'duplicate acquisition profile');
  const archiveReaders=new Map<string,Read>();
  const acquired=definitions.map(a=>{
    let retained=archiveReaders.get(a.archive.sha256);if(!retained){retained=readEbirdArchive(a.archive,read);archiveReaders.set(a.archive.sha256,retained);}
    const receipt=JSON.parse(decode(readEbirdPinned(a.receipt,retained)));readEbirdPinned(a.recipe,retained);
    check(receipt.recipe?.path===a.recipe.path&&receipt.recipe?.sha256===a.recipe.sha256&&receipt.automaticRetries===0&&receipt.providerWrites===0,'acquisition recipe or write lineage differs');
    check(a.repositoryBaseCommit===null?receipt.repositoryBaseCommit===undefined:receipt.repositoryBaseCommit===a.repositoryBaseCommit,'actual acquisition repository identity differs');
    check(Date.parse(receipt.startedAt)<=Date.parse(receipt.finishedAt)&&Date.parse(receipt.finishedAt)<=Date.parse(method.reviewedAt),'acquisition chronology differs');
    const responses=z.array(response).min(1).parse(a.name==='metadata'?receipt.receipts:receipt.responses);
    const decoded=new Map<string,Buffer>();
    for(const ref of responses){check((ref.finalUrl===undefined||ref.finalUrl===ref.url)&&Date.parse(receipt.startedAt)<=Date.parse(ref.retrievedAt)&&Date.parse(ref.retrievedAt)<=Date.parse(receipt.finishedAt),'source response chronology or identity differs');const raw=gunzipSync(readEbirdPinned(only(ref),retained),{maxOutputLength:20000000});check(raw.length===ref.decodedBytes&&sha256(raw)===ref.decodedSha256&&!decoded.has(ref.path),'source response bytes differ');decoded.set(ref.path,raw);}
    return {definition:a,receipt,responses,decoded,retained};
  });
  const get=(name:z.infer<typeof acquisition>['name'])=>acquired.find(a=>a.definition.name===name)!;
  const initial=get('search-initial'),resume=get('search-resume'),originalAcquisition=get('selected-originals');
  check(initial.receipt.paginationComplete===false&&resume.receipt.paginationComplete===false,'partial search cannot be reclassified as complete');
  check(resume.receipt.parentReceipt?.path===initial.definition.receipt.path&&resume.receipt.parentReceipt?.sha256===initial.definition.receipt.sha256&&Date.parse(initial.receipt.finishedAt)<=Date.parse(resume.receipt.startedAt),'search resume lineage differs');
  check(eq(initial.receipt.parameters,resume.receipt.parameters),'resume query differs');
  const parameters=initial.receipt.parameters,taxa=Object.entries(method.taxa);check(taxa.length===1,'selected profile requires one exact taxon');
  const [speciesId,taxon]=taxa[0];check(parameters.datasetKey===EBIRD_DATASET&&parameters.country==='US'&&parameters.year==='2024'&&parameters.taxonKey===String(taxon.taxonKey)&&parameters.limit==='300','search taxon or dataset predicate differs');
  const records=new Map<number,{record:EbirdRecord;response:z.infer<typeof response>;rowIndex:number}>();let declared:number|null=null,pageIndex=0;
  for(const acq of [initial,resume])for(const ref of acq.responses){const url=new URL(ref.url),page=JSON.parse(decode(acq.decoded.get(ref.path)!));check(url.origin==='https://api.gbif.org'&&url.pathname==='/v1/occurrence/search'&&eq(Object.fromEntries(url.searchParams),{...parameters,offset:String(pageIndex*300)}),'partial search URL differs');check(ref.page===pageIndex&&ref.offset===pageIndex*300&&page.offset===pageIndex*300&&page.limit===300&&page.endOfRecords===false&&ref.endOfRecords===false&&Array.isArray(page.results)&&page.results.length===300,'contiguous retained partial page differs');check(Number.isSafeInteger(page.count)&&page.count>0&&(declared===null||declared===page.count)&&ref.declaredCount===page.count&&ref.rows===page.results.length,'partial declared count differs');declared=page.count;for(const [rowIndex,r] of page.results.entries()){const k=key.parse(r.key);check(!records.has(k)&&r.datasetKey===EBIRD_DATASET&&r.countryCode==='US'&&r.year===2024&&r.speciesKey===taxon.taxonKey,'duplicate or outside-query record');records.set(k,{record:r,response:ref,rowIndex});}pageIndex++;}
  check(declared!==null&&records.size<declared&&resume.receipt.combinedRows===records.size&&resume.receipt.priorRows===initial.receipt.rowsReceived&&resume.receipt.rowsReceived===resume.responses.length*300&&initial.receipt.rowsReceived===initial.responses.length*300,'partial source totals differ');
  const acq=originalAcquisition,receipt=acq.receipt;
  check(receipt.kind==='ebird-selected-original-field-acquisition'&&receipt.completed===true&&receipt.errors.length===0&&receipt.authenticatedRequests===0&&receipt.sourceId===EBIRD_SOURCE&&receipt.datasetKey===EBIRD_DATASET&&receipt.speciesId===speciesId&&receipt.scientificName===taxon.scientificName&&receipt.taxonKey===taxon.taxonKey&&receipt.sourceYear===2024,'complete selected-original acquisition differs');
  check(eq(receipt.parentSourceReceipts,[only(initial.definition.receipt),only(resume.definition.receipt)])&&Date.parse(resume.receipt.finishedAt)<=Date.parse(receipt.startedAt),'selected originals parent lineage differs');
  const diagnostic=JSON.parse(decode(readEbirdPinned(file.parse(receipt.parentDiagnostic),initial.retained)));check(diagnostic.pagination.complete===false&&diagnostic.pagination.receivedRows===records.size&&diagnostic.pagination.declaredCount===declared&&eq(diagnostic.receipts,receipt.parentSourceReceipts),'pinned parent diagnostic differs');
  const selections=z.array(z.object({key,pair,stateCode:z.string(),responsePath:safePath,responseSha256:hash,rowIndex:z.number().int().nonnegative(),eventDate:z.string(),county:z.string(),state:z.string(),occurrenceId:z.string()}).passthrough()).min(1).parse(receipt.selection);check(unique(selections.map(s=>s.key))&&receipt.maximumRequests===selections.length&&acq.responses.length===selections.length,'selected original coverage differs');
  const originals=new Map<number,{record:EbirdRecord;response:z.infer<typeof response>}>();
  for(const ref of acq.responses){const original=z.record(z.string(),z.unknown()).parse(JSON.parse(decode(acq.decoded.get(ref.path)!))),k=key.parse(original.key),selection=selections.find(s=>s.key===k);check(selection&&ref.key===k&&ref.pair===selection.pair&&ref.url==='https://api.gbif.org/v1/occurrence/'+k+'/verbatim'&&original.datasetKey===EBIRD_DATASET&&!originals.has(k),'selected original locator differs');originals.set(k,{record:original,response:ref});}
  const counties=JSON.parse(decode(read('src/data/research/county-equivalent-registry.json'))).countyEquivalents as EbirdCounty[];
  const selectedPairs=[...new Set(selections.map(s=>s.pair))].sort();
  for(const p of selectedPairs){const [fips,id]=p.split(':'),county=counties.find(c=>c.countyFips===fips&&c.status==='active');check(county&&id===speciesId,'selected current county or species differs');const material=[...records.values()].filter(v=>v.record.stateProvince===county.stateName&&[county.shortName,county.legalName,...county.aliases].includes(String(v.record.county)));const expected=material.sort((a,b)=>String(b.record.eventDate).localeCompare(String(a.record.eventDate))||Number(a.record.key)-Number(b.record.key)).slice(0,2).map(v=>Number(v.record.key));check(eq(sorted(selections.filter(s=>s.pair===p).map(s=>s.key)),sorted(expected)),'selected witness rule differs');}
  for(const s of selections){const v=records.get(s.key);check(v&&s.stateCode===counties.find(c=>c.countyFips===s.pair.split(':')[0])?.stateCode&&s.responsePath===v.response.path&&s.responseSha256===v.response.sha256&&s.rowIndex===v.rowIndex&&s.eventDate===v.record.eventDate&&s.county===v.record.county&&s.state===v.record.stateProvince&&s.occurrenceId===v.record.occurrenceID,'selected interpreted witness locator differs');}
  const metadata=get('metadata'),datasets=metadata.responses.filter(r=>r.url==='https://api.gbif.org/v1/dataset/'+EBIRD_DATASET);check(datasets.length===1&&metadata.receipt.errors.length===0,'dataset response differs');const dataset=JSON.parse(decode(metadata.decoded.get(datasets[0].path)!));check(dataset.key===EBIRD_DATASET&&dataset.license===EBIRD_LICENSE&&dataset.doi==='10.15468/aomfnb'&&dataset.publishingOrganizationKey==='e2e717bf-551a-4917-bdc9-4fa0f342c530','dataset publisher or license differs');const tags=z.array(z.object({name:z.string(),value:z.string(),namespace:z.string(),created:z.string()}).passthrough()).parse(dataset.machineTags);
  const context=get('context'),urls=['https://api.gbif.org/v1/dataset/'+EBIRD_DATASET+'/document','https://gbif.github.io/gbif-api/apidocs/src-html/org/gbif/api/vocabulary/TagName.html','https://support.ebird.org/en/support/solutions/articles/48000795278-the-ebird-review-process','https://support.ebird.org/en/support/solutions/articles/48000948757-ebird-faqs','https://support.ebird.org/en/support/solutions/articles/48000838205-download-ebird-data'];check(context.definition.repositoryBaseCommit===null&&context.receipt.errors.length===0&&eq(context.responses.map(r=>r.url).sort(),urls.sort()),'primary method context differs');
  const cc=collectionContextSchema.parse(method.collectionContext),retainedContext=readEbirdArchive(cc.archive,read),cr=JSON.parse(decode(readEbirdPinned(cc.receipt,retainedContext)));readEbirdPinned(cc.recipe,retainedContext);
  check(cr.kind==='ebird-atlas-portal-primary-context'&&cr.repositoryBaseCommit===cc.repositoryBaseCommit&&cr.recipe.path===cc.recipe.path&&cr.recipe.sha256===cc.recipe.sha256&&cr.automaticRetries===0&&cr.providerWrites===0&&Date.parse(cr.startedAt)<=Date.parse(cr.finishedAt)&&Date.parse(cr.finishedAt)<=Date.parse(method.reviewedAt),'atlas context lineage differs');
  const contextResponses=z.array(response).length(2).parse(cr.responses),expectedUrls=['https://ebird.org/atlasnc/about/setting-your-portal','https://ebird.org/atlasny/news/big-atlas-weekend-2023'];check(eq(contextResponses.map(r=>r.url).sort(),expectedUrls.sort()),'atlas primary URLs differ');
  for(const ref of contextResponses){const b=gunzipSync(readEbirdPinned(only(ref),retainedContext),{maxOutputLength:2000000});check(b.length===ref.decodedBytes&&sha256(b)===ref.decodedSha256&&Date.parse(cr.startedAt)<=Date.parse(ref.retrievedAt)&&Date.parse(ref.retrievedAt)<=Date.parse(cr.finishedAt),'atlas primary response differs');const html=decode(b);check(html.includes('Cornell')&&(ref.url.includes('atlasnc')?html.includes('North Carolina Bird Atlas'):html.includes('NY Breeding Bird Atlas portal')),'atlas primary context content differs');}
  return {acquired,records,originals,selections,selectedPairs,counties,tags,declared,retainedRows:records.size,originalAcquisition};
}

export function loadEbirdSelectedMethod(plan:EbirdSelectedPlan,read:Read){
  methodPath.parse(plan.methodReviewPath);hash.parse(plan.methodReviewSha256);const bytes=read(plan.methodReviewPath);check(sha256(bytes)===plan.methodReviewSha256,'method hash differs');const method=ebirdSelectedMethodSchema.parse(JSON.parse(decode(bytes))),source=loadEbirdSelectedSource(method,read);
  const reviews=method.independentReviews.map(ref=>{const proposal=JSON.parse(decode(readEbirdPinned(ref.proposal,read))),review=adapterReview.parse(proposal.adapterReview),retention=JSON.parse(decode(readEbirdPinned(ref.retention,read)));readEbirdPinned(ref.recipe,read);check(review.actorId===ref.actorId&&review.baseSha===ref.baseSha&&ref.actorId!=='MAIN','independent reviewer differs');check(retention.kind==='main-retained-independent-method-proposal'&&retention.originalCommit===ref.originalCommit&&retention.actorId===ref.actorId&&retention.baseSha===ref.baseSha&&eq(retention.files,[ref.proposal,ref.recipe])&&retention.acceptedDeterminations===0&&retention.canonicalEvents===0&&retention.mainOfflineVerification.passed===true&&Date.parse(retention.recordedAt)<=Date.parse(method.reviewedAt),'independent review retention differs');return {definition:ref,review};});check(unique(reviews.map(r=>r.definition.actorId)),'reviewers are not distinct');
  const pairReviews=reviews.flatMap(r=>r.review.pairs.map(p=>({...p,actorId:r.definition.actorId})));check(unique(pairReviews.map(p=>p.pairKey))&&eq(pairReviews.filter(p=>p.disposition==='supported').map(p=>p.pairKey).sort(),method.approvedPairs)&&eq(pairReviews.filter(p=>p.disposition==='held').map(p=>p.pairKey).sort(),method.heldPairs),'reviewed pair disposition differs');const covered=[...method.approvedPairs,...method.heldPairs,...method.deferredPairs];check(unique(covered)&&eq(covered.sort(),source.selectedPairs),'selected pairs must be reviewed or explicitly deferred');
  for(const p of pairReviews){const expected=source.selections.filter(s=>s.pair===p.pairKey).map(s=>s.key);check(unique(p.recordKeys)&&eq(p.recordKeys,sorted(expected))&&unique(p.heldKeys)&&eq(p.heldKeys,sorted(p.heldKeys))&&p.heldKeys.every(k=>p.recordKeys.includes(k)),'selected original review key scope differs');check(p.disposition==='held'?p.primaryKey===null:p.primaryKey!==null&&p.recordKeys.includes(p.primaryKey)&&!p.heldKeys.includes(p.primaryKey),'primary witness is not independently supported');}
  return {method,...source,reviews,pairReviews};
}

export function ebirdSelectedInputPaths(plan:EbirdSelectedPlan,read:Read){const {method}=loadEbirdSelectedMethod(plan,read);return [...new Set(['src/lib/research/ebird-original-observations.ts','src/lib/research/ebird-selected-original-observations.ts','scripts/research/adapters/ebird-selected-original-observations.ts',plan.methodReviewPath,method.collectionContext.archive.path,...method.acquisitions.map(a=>a.archive.path),...method.independentReviews.flatMap(r=>[r.proposal.path,r.recipe.path,r.retention.path])])].sort();}

export function buildEbirdSelectedResult(context:SourceAdapterContext, read:Read):SourceAdapterResult {
  const p=ebirdSelectedParametersSchema.parse(context.parameters),loaded=loadEbirdSelectedMethod(p,read),{method,records,originals,pairReviews}=loaded;
  z.string().datetime().parse(context.runStartedAt);
  check(context.sourceId===EBIRD_SOURCE&&context.stateCode===p.stateCode&&Date.parse(method.reviewedAt)<=Date.parse(context.runStartedAt),'run identity or chronology differs');
  const requested=context.requestedPairs.map(r=>r.countyFips+':'+r.speciesId).sort();
  check(unique(requested)&&stableJson(requested)===stableJson(p.candidatePairs)&&p.candidateLimit===requested.length&&requested.every(k=>method.approvedPairs.includes(k)&&!method.heldPairs.includes(k)),'requested approved scope differs');
  const counties=JSON.parse(decode(read('src/data/research/county-equivalent-registry.json'))).countyEquivalents as EbirdCounty[];
  const recordByKey=new Map([...records].map(([key,value])=>[key,value.record]));
  const resolved=new Map<number,ReturnType<typeof qualifyEbirdOriginal>>();
  for(const review of pairReviews){
    const [countyFips,speciesId]=review.pairKey.split(':'),taxon=method.taxa[speciesId];check(taxon,'unreviewed taxon');
    for(const key of review.recordKeys){
      const record=recordByKey.get(key)!,original=originals.get(key)!,value=qualifyEbirdOriginal(record,original.record,counties,taxon.scientificName,taxon.taxonKey,loaded.tags,EBIRD_SELECTED_COLLECTIONS);
      check(record.year===method.sourceYear&&record.speciesKey===taxon.taxonKey,'record differs from acquired search predicate');
      if(!review.heldKeys.includes(key)&&review.disposition==='supported')check(value.reason===null&&value.county?.countyFips===countyFips&&Date.parse(value.date!)<=Date.parse(original.response.retrievedAt),'supported original witness fails: '+key+' '+value.reason);
      resolved.set(key,value);
    }
  }
  const result:SourceAdapterResult={completedAt:context.runStartedAt,assertions:[],reviews:[],rejections:[],outcomes:[],artifacts:[],upstreamRequests:[],candidateRecordCount:0,duplicateRecordCount:0,errors:[],warnings:method.limitations};
  const actor=EBIRD_ADAPTER+'@'+EBIRD_SELECTED_VERSION,eventId=(name:string,value:unknown)=>name+'-'+sha256(stableJson(value)),witnesses:unknown[]=[];
  for(const target of context.requestedPairs){
    const pair=target.countyFips+':'+target.speciesId,review=pairReviews.find(r=>r.pairKey===pair)!,taxon=method.taxa[target.speciesId];
    check(taxon.scientificName===target.scientificName&&review.disposition==='supported'&&review.primaryKey!==null,'target differs from reviewed source');
    const primary=recordByKey.get(review.primaryKey)!,original=originals.get(review.primaryKey)!,qualified=resolved.get(review.primaryKey)!;
    check(qualified.county?.stateCode===p.stateCode&&qualified.county.countyFips===target.countyFips,'target source county/state differs');
    const accepted=review.recordKeys.filter(key=>!review.heldKeys.includes(key)),dates=accepted.map(key=>resolved.get(key)!.date!).sort();
    const sourceRows=review.recordKeys.map(key=>({key,disposition:review.heldKeys.includes(key)?'independent-record-hold':'supported-historical-occurrence',originalResponse:only(originals.get(key)!.response),originalResponseDecodedSha256:originals.get(key)!.response.decodedSha256,originalFields:originals.get(key)!.record,interpretedFields:recordByKey.get(key)!}));
    const payload={pairKey:pair,methodReviewPath:p.methodReviewPath,methodReviewSha256:p.methodReviewSha256,searchResponseHashes:review.recordKeys.map(key=>({key,sha256:records.get(key)!.response.sha256})),primaryKey:review.primaryKey,acceptedKeys:accepted,heldKeys:review.heldKeys,originalResponseHashes:sourceRows.map(r=>({key:r.key,sha256:r.originalResponse.sha256}))};
    const assertionId=eventId('ebird-selected-original-assertion',{runId:context.runId,...payload}),url='https://www.gbif.org/occurrence/'+review.primaryKey,caveats=[method.attribution,...method.limitations];
    result.assertions.push({schemaVersion:1,eventId:assertionId,event_type:'evidence.asserted',created_at:context.runStartedAt,actor_type:'adapter',actor_id:actor,run_id:context.runId,source_id:EBIRD_SOURCE,state_code:p.stateCode,county_fips:target.countyFips,species_id:target.speciesId,claim_type:'recorded-present',evidence_kind:'occurrence',scope:'point',source_record_id:String(primary.occurrenceID),source_url:url,source_record_date:qualified.date!,retrieved_at:original.response.retrievedAt,
      taxon_match:{method:'Independently reviewed exact original binomial, accepted GBIF species key and retained taxonomic classifications; unresolved Avibase concept annotation retained.',target_scientific_name:target.scientificName,source_scientific_name:String(original.record[term('scientificName')]),source_taxon_key:String(taxon.taxonKey)},
      geography_match:{method:'Exact original publisher county name or registered alias within its original state resolves uniquely to an active county. Coordinates are consistency evidence only; missing uncertainty does not change this county authority.',source_state:String(original.record[term('stateProvince')]),source_county:String(original.record[term('county')]),county_fips:target.countyFips},
      temporal_scope:'Selected original observation date '+qualified.date+'; additional reviewed records span '+dates[0]+' through '+dates.at(-1)+'.',spatial_scope:'Recorded bird observation locations in the explicit publisher county; no countywide abundance or prevalence claim.',survey_scope:'Annual EOD occurrence records without sampling-effort or complete-checklist metadata.',normalized_payload_hash:sha256(stableJson(payload)),caveats,notes:['Independent source review actor: '+review.actorId+'. Machine validation reconstructs that reviewed source contract; it does not claim individual human expert approval.','Distinct source records may share birds or observation events; counts are not summed.','Original source fields and response hashes: ebird-selected-original-witnesses.json.']});
    result.reviews.push({schemaVersion:1,eventId:eventId('ebird-selected-original-review',{assertionId}),event_type:'evidence.reviewed',created_at:context.runStartedAt,actor_type:'adapter',actor_id:actor,run_id:context.runId,source_id:EBIRD_SOURCE,state_code:p.stateCode,county_fips:target.countyFips,species_id:target.speciesId,references:{assertion_event_id:assertionId},review_level:'machine-validated',decision:'accepted',publication_eligible:true,reason_codes:['exact-original-taxon','exact-publisher-county','positive-human-observation','independent-original-field-review','qualified-dataset-metadata'],notes:['Original and interpreted source bytes, current registry identity and independently selected witness were reconstructed offline.']});
    const rejectionIds:string[]=[];
    if(review.heldKeys.length){const id=eventId('ebird-selected-original-rejection',{runId:context.runId,pair,keys:review.heldKeys});rejectionIds.push(id);result.rejections.push({schemaVersion:1,rejection_id:id,created_at:context.runStartedAt,actor_type:'adapter',actor_id:actor,run_id:context.runId,source_id:EBIRD_SOURCE,candidate_locator:p.methodReviewPath+'#held-original-keys='+review.heldKeys.join(','),candidate_taxon:target.scientificName,candidate_geography:target.countyFips,normalized_target:{state_code:p.stateCode,county_fips:target.countyFips,species_id:target.speciesId},reason_code:'record-failed',supporting_notes:['Independent original-field record holds are retained in the pinned proposal; no negative determination follows.']});}
    result.outcomes.push({schemaVersion:1,outcome_id:eventId('ebird-selected-original-outcome',{runId:context.runId,pair}),run_id:context.runId,source_id:EBIRD_SOURCE,state_code:p.stateCode,county_fips:target.countyFips,species_id:target.speciesId,status:'evidence-found',scope_complete:true,recorded_at:context.runStartedAt,assertion_event_ids:[assertionId],rejection_ids:rejectionIds,query_urls:review.recordKeys.map(key=>originals.get(key)!.response.url),notes:['The explicitly selected finite original-record set for this pair was completely retrieved and reviewed. scope_complete refers only to that listed record set. The parent public search remains incomplete; this outcome does not claim a completed national search, exhaustive source-family screen, all years or county research protocol.']});
    result.candidateRecordCount+=review.recordKeys.length;
    witnesses.push({...payload,independentActor:review.actorId,selectedDate:qualified.date,selectedRecordUrl:url,sourceRows});
  }
  result.artifacts.push({filename:'ebird-selected-original-witnesses.json',mediaType:'application/json',contents:JSON.stringify({schemaVersion:1,method:EBIRD_SELECTED_METHOD,methodReviewPath:p.methodReviewPath,methodReviewSha256:p.methodReviewSha256,datasetKey:EBIRD_DATASET,datasetDoi:'10.15468/aomfnb',license:EBIRD_LICENSE,acquisitions:method.acquisitions,parentSearch:{paginationComplete:false,retainedRows:loaded.retainedRows,declaredRows:loaded.declared},selectedRecordRequests:loaded.originalAcquisition.responses,witnesses,qualification:'Original raw HTTP response bytes remain in hash-pinned archives. Only the selected original-record set is fully reviewed; the15000-record parent search remains incomplete. Parsed fields here are derived representations. Offline run identity is distinct from original acquisition code; no fresh request occurred.'},null,2)+'\n'});
  return result;
}
