"use client";
import { useEffect, useState, type FormEvent } from "react";
import { request, TURNSTILE_SITE_KEY } from "@/lib/participation/client";
import { EMPTY_PREFERENCES, type Preferences } from "@/lib/participation/contracts";
import { Challenge, Frame, Honeypot, Notice, PreferenceFields, styles, useConfig } from "./shared";
export function PreferencesForm(){
 const {config}=useConfig(),[token,setToken]=useState(""),[kind,setKind]=useState(""),[preferences,setPreferences]=useState<Preferences>(EMPTY_PREFERENCES),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[challenge,setChallenge]=useState(""),[reset,setReset]=useState(0);
 useEffect(()=>{const hash=new URLSearchParams(location.hash.slice(1));for(const purpose of ["confirm","preferences","unsubscribe"]){const value=hash.get(purpose);if(value&&/^[a-f0-9]{64}$/.test(value)){setToken(value);setKind(purpose);break;}}history.replaceState(null,"",location.pathname);},[]);
 async function apply(action:string){setBusy(true);setError("");try{const result=await request<{preferences?:Preferences}>("preferences",{token,action,preferences});if(action==="read"&&result.preferences){setPreferences(result.preferences);setLoaded(true);}else{setMessage(action==="unsubscribe"?"You have been unsubscribed from all IsItUSA updates.":"Your email choices are saved.");setToken("");setLoaded(false);}}catch(err){setError(err instanceof Error?err.message:"Please try again.");}finally{setBusy(false);}}
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget);try{const result=await request<{message:string}>("preferences-email",{email:data.get("email"),challenge,website:data.get("website")});setMessage(result.message);}catch(err){setError(err instanceof Error?err.message:"Please try again.");}finally{setBusy(false);setReset(n=>n+1);setChallenge("");}}
 return <Frame title="Make these emails yours." description="Change what you follow, or pause every update. You do not need an account.">
 <div className={styles.form} style={{maxWidth:680}}>{error&&<Notice error>{error}</Notice>}{message&&<Notice success>{message}</Notice>}
 {token?<>{kind==="confirm"?<><Notice>Confirm the email choices you made on IsItUSA. Nothing changes until you press the button.</Notice><button className={styles.button} disabled={busy} onClick={()=>void apply("confirm")}>Confirm my updates</button></>:kind==="unsubscribe"?<button className={styles.button} disabled={busy} onClick={()=>void apply("unsubscribe")}>Unsubscribe from all updates</button>:<>{!loaded?<button className={styles.button} disabled={busy} onClick={()=>void apply("read")}>Open my preferences</button>:<><PreferenceFields key={token} value={preferences} onChange={setPreferences}/><div className={styles.row}><button className={styles.button} disabled={busy} onClick={()=>void apply("save")}>Save my choices</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>void apply("unsubscribe")}>Unsubscribe from everything</button></div></>}</>}</>:
 <form className={styles.form} onSubmit={send}>{config&&!config.email&&<Notice>Email preferences will open when updates launch.</Notice>}<fieldset disabled={!config?.email||!TURNSTILE_SITE_KEY||busy}><label className={styles.field}>Email address<input type="email" name="email" required className={styles.input} autoComplete="email"/></label><Honeypot/>{config?.email&&<Challenge action="preferences-email" onToken={setChallenge} reset={reset}/>}<button disabled={!challenge||busy} className={styles.button}>Email me a private link</button></fieldset></form>}</div></Frame>;
}
