"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowUpRight, Copy, Heart, Leaf, MapPin, ScanSearch } from "lucide-react";
import { request, TURNSTILE_SITE_KEY } from "@/lib/participation/client";
import { cryptoUri, donationAmount } from "@/lib/participation/contracts";
import { Challenge, Frame, Notice, ServiceStatus, styles, useConfig } from "./shared";
export function SupportForm(){
 const {config,error:configError,retry}=useConfig(),[amount,setAmount]=useState("10"),[challenge,setChallenge]=useState(""),[reset,setReset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState("");
 const ready=Boolean(config?.payments&&TURNSTILE_SITE_KEY);
 async function checkout(e:FormEvent){e.preventDefault();setError("");try{donationAmount(amount);setBusy(true);const result=await request<{url:string}>("checkout",{amount,challenge});const url=new URL(result.url);if(url.protocol!=="https:"||url.hostname!=="checkout.stripe.com")throw new Error("Checkout is unavailable. Please try again.");location.assign(url.href);}catch(err){setError(err instanceof Error?err.message:"Please try again.");setBusy(false);setReset(n=>n+1);setChallenge("");}}
 return <Frame title="Help your community stay informed." description="A neighbor, a gardening group, a local park. Help the people around you find useful information about invasive species and know where to turn next." aside={<><h2>What your support helps build</h2><p>Clearer species profiles, traceable county records, and tools that make the research easier to use.</p><details className={styles.supportDetails}><summary>About contributions</summary><p>IsItUSA is an independent initiative in the United States, not a registered nonprofit. We do not offer tax-deductible donations.</p><p>Email updates are a separate choice. A contribution will never sign you up automatically.</p></details><Link href="/about" className="text-link">Why we are building IsItUSA <ArrowUpRight size={16} aria-hidden="true"/></Link></>}>
 <section className={styles.supportActions} aria-labelledby="help-today"><h2 id="help-today">A few ways to help today</h2><div>
 <Link href="/"><MapPin size={24} aria-hidden="true"/><span><strong>Bring the map to your community</strong><small>Look up your county and share its records with a neighbor or local group.</small></span><ArrowUpRight size={19} aria-hidden="true"/></Link>
 <Link href="/species"><Leaf size={24} aria-hidden="true"/><span><strong>Pass on a useful species profile</strong><small>Find a plant or animal people are asking about, with sources they can check.</small></span><ArrowUpRight size={19} aria-hidden="true"/></Link>
 <Link href="/report"><ScanSearch size={24} aria-hidden="true"/><span><strong>Learn how to document a sighting</strong><small>See what to record and where to report what you found.</small></span><ArrowUpRight size={19} aria-hidden="true"/></Link>
 </div></section>
 <div className={styles.supportAvailability}><ServiceStatus config={config} error={configError} ready={ready} retry={retry}><strong>Contributions are coming later.</strong><p>Card and crypto contributions are not open yet. You can help now by sharing the atlas.</p></ServiceStatus></div>
 {ready&&<section><h2 className="text-2xl mb-5">Choose your contribution</h2><form className={styles.form} onSubmit={checkout} aria-busy={busy}>
 <fieldset disabled={!ready||busy}><div className={styles.row}>{["5","10","25","50"].map(value=><button type="button" aria-pressed={amount===value} key={value} className={`${styles.button} ${amount!==value?styles.secondary:""}`} onClick={()=>setAmount(value)}>$ {value}</button>)}</div>
 <label className={styles.field}>Amount in U.S. dollars<input className={styles.input} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required aria-describedby="amount-note"/><span id="amount-note" className={styles.hint}>Choose an amount from $1 to $10,000.</span></label>
 {ready&&<Challenge action="checkout" onToken={setChallenge} reset={reset}/>}<button className={styles.button} disabled={!challenge||busy}><Heart size={18} aria-hidden="true"/>{busy?"Opening secure checkout...":"Continue to Stripe"}<ArrowUpRight size={16} aria-hidden="true"/></button>
 <p className={styles.hint}>Stripe handles payment details and receipts. Your receipt confirms whether payment was completed. Read our <a className="text-link" href="/terms">support terms</a>.</p></fieldset>{error&&<Notice error>{error}</Notice>}</form></section>}
 {config&&config.wallets.length>0&&<section className={styles.section}><h2>Contribute with crypto</h2>{config.wallets.map(wallet=><article key={wallet.id} className={styles.wallet}><h3>{wallet.asset}</h3><p className={styles.hint}>{wallet.network} only</p><code>{wallet.address}</code><div className={styles.row}><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>{if(!navigator.clipboard){setError("Copy is unavailable. Select the full address above.");return;}navigator.clipboard.writeText(wallet.address).then(()=>setCopied(wallet.id)).catch(()=>setError("Copy is unavailable. Select the full address above."));}}><Copy size={16} aria-hidden="true"/>{copied===wallet.id?"Copied":"Copy address"}</button>{cryptoUri(wallet)&&<a href={cryptoUri(wallet)!} className={styles.button}>Open wallet<ArrowUpRight size={16} aria-hidden="true"/></a>}</div><p className={styles.hint}>Check the full address and network in your wallet before sending. Crypto transfers cannot be reversed by IsItUSA.</p></article>)}</section>}{!ready&&error&&<Notice error>{error}</Notice>}</Frame>;
}
