"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowUpRight, Copy, Heart } from "lucide-react";
import { request, TURNSTILE_SITE_KEY } from "@/lib/participation/client";
import { cryptoUri, donationAmount } from "@/lib/participation/contracts";
import { Challenge, Frame, Notice, ServiceStatus, styles, useConfig } from "./shared";
export function SupportForm(){
 const {config,error:configError,retry}=useConfig(),[amount,setAmount]=useState("10"),[challenge,setChallenge]=useState(""),[reset,setReset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState("");
 const ready=Boolean(config?.payments&&TURNSTILE_SITE_KEY);
 async function checkout(e:FormEvent){e.preventDefault();setError("");try{donationAmount(amount);setBusy(true);const result=await request<{url:string}>("checkout",{amount,challenge});const url=new URL(result.url);if(url.protocol!=="https:"||url.hostname!=="checkout.stripe.com")throw new Error("Checkout is unavailable. Please try again.");location.assign(url.href);}catch(err){setError(err instanceof Error?err.message:"Please try again.");setBusy(false);setReset(n=>n+1);setChallenge("");}}
 return <Frame title="Help more people find reliable answers." description="A useful atlas takes careful research and clear, accessible tools. We are building both, so anyone can learn about the invasive species recorded where they live." aside={<><h2>About contributions</h2><p>IsItUSA is an independent initiative in the United States, not a registered nonprofit. We do not offer tax-deductible donations.</p><p>Email updates will be a separate choice. Supporting IsItUSA will never sign you up automatically.</p><a href="/join" className="text-link">See our plans for email updates</a></>}>
 <ServiceStatus config={config} error={configError} ready={ready} retry={retry}><strong>We are not accepting contributions yet.</strong><p>We are setting up card and crypto contributions. In the meantime, there are other useful ways to help.</p></ServiceStatus>
 {config&&!ready&&<section className={styles.section}><h2>Start with someone you know.</h2><p className={styles.hint}>Send a county map to a neighbor, a species profile to a gardening group, or the atlas to someone who cares for a local park. A useful introduction can go a long way.</p><div className={styles.row}><Link href="/species" className={styles.button}>Browse species</Link><a href="/report" className="text-link">Learn how to report a sighting</a></div></section>}
 {ready&&<section><h2 className="text-2xl mb-5">Choose your contribution</h2><form className={styles.form} onSubmit={checkout} aria-busy={busy}>
 <fieldset disabled={!ready||busy}><div className={styles.row}>{["5","10","25","50"].map(value=><button type="button" aria-pressed={amount===value} key={value} className={`${styles.button} ${amount!==value?styles.secondary:""}`} onClick={()=>setAmount(value)}>$ {value}</button>)}</div>
 <label className={styles.field}>Amount in U.S. dollars<input className={styles.input} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required aria-describedby="amount-note"/><span id="amount-note" className={styles.hint}>Choose an amount from $1 to $10,000.</span></label>
 {ready&&<Challenge action="checkout" onToken={setChallenge} reset={reset}/>}<button className={styles.button} disabled={!challenge||busy}><Heart size={18} aria-hidden="true"/>{busy?"Opening secure checkout...":"Continue to Stripe"}<ArrowUpRight size={16} aria-hidden="true"/></button>
 <p className={styles.hint}>Stripe handles payment details and receipts. Your receipt confirms whether payment was completed. Read our <a className="text-link" href="/terms">support terms</a>.</p></fieldset>{error&&<Notice error>{error}</Notice>}</form></section>}
 {config&&config.wallets.length>0&&<section className={styles.section}><h2>Contribute with crypto</h2>{config.wallets.map(wallet=><article key={wallet.id} className={styles.wallet}><h3>{wallet.asset}</h3><p className={styles.hint}>{wallet.network} only</p><code>{wallet.address}</code><div className={styles.row}><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>{if(!navigator.clipboard){setError("Copy is unavailable. Select the full address above.");return;}navigator.clipboard.writeText(wallet.address).then(()=>setCopied(wallet.id)).catch(()=>setError("Copy is unavailable. Select the full address above."));}}><Copy size={16} aria-hidden="true"/>{copied===wallet.id?"Copied":"Copy address"}</button>{cryptoUri(wallet)&&<a href={cryptoUri(wallet)!} className={styles.button}>Open wallet<ArrowUpRight size={16} aria-hidden="true"/></a>}</div><p className={styles.hint}>Check the full address and network in your wallet before sending. Crypto transfers cannot be reversed by IsItUSA.</p></article>)}</section>}{!ready&&error&&<Notice error>{error}</Notice>}</Frame>;
}
