"use client";
import { useState, type FormEvent } from "react";
import { ArrowUpRight, Copy, Heart } from "lucide-react";
import { request, TURNSTILE_SITE_KEY } from "@/lib/participation/client";
import { cryptoUri, donationAmount } from "@/lib/participation/contracts";
import { Challenge, Frame, Notice, styles, useConfig } from "./shared";
export function SupportForm(){
 const {config,error:configError}=useConfig(),[amount,setAmount]=useState("10"),[challenge,setChallenge]=useState(""),[reset,setReset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState("");
 const ready=Boolean(config?.payments&&TURNSTILE_SITE_KEY);
 async function checkout(e:FormEvent){e.preventDefault();setError("");try{donationAmount(amount);setBusy(true);const result=await request<{url:string}>("checkout",{amount,challenge});const url=new URL(result.url);if(url.protocol!=="https:"||url.hostname!=="checkout.stripe.com")throw new Error("Checkout is unavailable. Please try again.");location.assign(url.href);}catch(err){setError(err instanceof Error?err.message:"Please try again.");setBusy(false);setReset(n=>n+1);setChallenge("");}}
 return <Frame title="Help keep good information growing." description="Your support helps IsItUSA review sources, improve the map, and make useful information easier to find." aside={<><h2>Independent, with a public purpose.</h2><p>IsItUSA is an independent initiative based in the United States. It is not a registered nonprofit, and we do not describe contributions as tax-deductible donations.</p><p>Supporting the work does not subscribe you to emails. You can choose those separately.</p><a href="/join" className="text-link">Choose your updates</a></>}>
 <section><h2 className="text-2xl mb-5">Give once. Make a difference.</h2><form className={styles.form} onSubmit={checkout}>
 {configError&&<Notice error>{configError}</Notice>}{config&&!ready&&<Notice>Online contributions are opening soon. Thank you for wanting to help.</Notice>}
 <fieldset disabled={!ready||busy}><div className={styles.row}>{["5","10","25","50"].map(value=><button type="button" aria-pressed={amount===value} key={value} className={`${styles.button} ${amount!==value?styles.secondary:""}`} onClick={()=>setAmount(value)}>$ {value}</button>)}</div>
 <label className={styles.field}>Amount in U.S. dollars<input className={styles.input} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required aria-describedby="amount-note"/><span id="amount-note" className={styles.hint}>Choose an amount from $1 to $10,000.</span></label>
 {ready&&<Challenge action="checkout" onToken={setChallenge} reset={reset}/>}<button className={styles.button} disabled={!challenge||busy}><Heart size={18} aria-hidden="true"/>{busy?"Opening secure checkout...":"Continue to Stripe"}<ArrowUpRight size={16} aria-hidden="true"/></button>
 <p className={styles.hint}>Stripe handles payment details and receipts. Your receipt confirms whether payment was completed. Read our <a className="text-link" href="/terms">support terms</a>.</p></fieldset>{error&&<Notice error>{error}</Notice>}</form></section>
 <section className={styles.section}><h2>Support with crypto</h2>{!config?.wallets.length?<p className={styles.hint}>Bitcoin, Monero, and Ethereum receiving addresses will appear here once they are ready and verified.</p>:config.wallets.map(wallet=><article key={wallet.id} className={styles.wallet}><h3>{wallet.asset}</h3><p className={styles.hint}>{wallet.network} only</p><code>{wallet.address}</code><div className={styles.row}><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>{navigator.clipboard.writeText(wallet.address).then(()=>setCopied(wallet.id)).catch(()=>setError("Copy is unavailable. Select the full address above."));}}><Copy size={16} aria-hidden="true"/>{copied===wallet.id?"Copied":"Copy address"}</button><a href={cryptoUri(wallet)??undefined} className={styles.button}>Open wallet<ArrowUpRight size={16} aria-hidden="true"/></a></div><p className={styles.hint}>Check the full address and network in your wallet before sending. Crypto transfers cannot be reversed by IsItUSA.</p></article>)}</section></Frame>;
}
