"use client";
import { useEffect, useState, type FormEvent } from "react";
import { backend } from "@/lib/participation/client";
import { Notice, styles } from "@/components/participation/shared";
export function CampaignDrafts(){
 const [drafts,setDrafts]=useState<{id:string;subject:string;stream:string;status:string}[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[saved,setSaved]=useState(false);
 useEffect(()=>{let active=true;backend().from("isitusa_campaigns").select("id,subject,stream,status").order("created_at",{ascending:false}).limit(20).then(result=>{if(!active)return;if(result.error)setError("Campaign drafts could not load.");else setDrafts(result.data);});return()=>{active=false;};},[revision]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setSaved(false);const form=e.currentTarget,data=new FormData(form);const result=await backend().rpc("isitusa_campaign",{stream:data.get("stream"),subject:data.get("subject"),body:data.get("body")});setBusy(false);if(result.error)setError(result.error.message);else{setSaved(true);form.reset();setRevision(n=>n+1);}}
 return <section className={styles.section}><h2>Write the next update.</h2><p className={styles.hint}>Prepare a species story or a way to help. Saving a draft does not send an email.</p><form className={styles.form} onSubmit={save} style={{marginTop:20}}><label className={styles.field}>Email choice<select name="stream" className={styles.select}><option value="facts">Get to know invasive species</option><option value="action">Ways to help</option></select></label><label className={styles.field}>Subject<input name="subject" required maxLength={150} className={styles.input}/></label><label className={styles.field}>Message<textarea name="body" required maxLength={10000} className={styles.textarea}/></label><button className={styles.button} disabled={busy}>Save draft</button>{error&&<Notice error>{error}</Notice>}{saved&&<Notice success>Draft saved. It has not been sent.</Notice>}</form>{drafts.length>0&&<ul className={styles.section}>{drafts.map(draft=><li className={styles.notice} key={draft.id}>{draft.subject} · {draft.stream} · {draft.status}</li>)}</ul>}</section>;
}
