"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { BookOpenCheck, Search, Save, ArrowUpRight } from "lucide-react";
import queue from "@/content/editorial-queue.json";
import { SPECIES_EDITORIAL } from "@/content/species-editorial";
import { backend } from "@/lib/participation/client";
import { Notice, styles } from "@/components/participation/shared";
import admin from "./admin.module.css";
type Task={species_id:string;status:string;draft:string;notes:string;sources:string[];version:number;updated_at?:string};
const states={queued:"Queued",in_progress:"In progress",in_review:"Ready for review",reviewed:"Reviewed"};
export function EditorialTracker({preview=false,canReview=false,onDirtyChange}:{preview?:boolean;canReview?:boolean;onDirtyChange?:(dirty:boolean)=>void}){
 const [tasks,setTasks]=useState<Record<string,Task>>({}),[batch,setBatch]=useState(1),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState(""),[notes,setNotes]=useState(""),[sources,setSources]=useState(""),[status,setStatus]=useState("in_progress"),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(preview){setLoading(false);return;}let current=true;(async()=>{try{const all:Record<string,Task>={};for(let offset=0;offset<3000;offset+=1000){const r=await backend().from("isitusa_editorial_tasks").select("*").order("species_id").range(offset,offset+999);if(r.error)throw new Error("The research queue could not load. Refresh the workspace to retry.");for(const t of r.data)all[t.species_id]=t;if(r.data.length<1000)break;}if(current)setTasks(all);}catch(e){if(current)setError(e instanceof Error?e.message:"Queue unavailable");}finally{if(current)setLoading(false);}})();return()=>{current=false;};},[preview]);
 useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false);},[dirty,onDirtyChange]);
 useEffect(()=>{if(!dirty)return;const leave=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave);},[dirty]);
 const stateFor=(id:string)=>tasks[id]?.status??(SPECIES_EDITORIAL[id]?"reviewed":"queued");
 const totals=useMemo(()=>{const n:Record<string,number>={queued:0,in_progress:0,in_review:0,reviewed:0};for(const row of queue)n[tasks[row.id]?.status??(SPECIES_EDITORIAL[row.id]?"reviewed":"queued")]++;return n;},[tasks]);
 const rows=queue.filter(row=>(query?`${row.commonName} ${row.scientificName}`.toLowerCase().includes(query.toLowerCase()):row.batch===batch)&&(filter==="all"||stateFor(row.id)===filter));
 const species=queue.find(row=>row.id===selected);
 function open(id:string){if(dirty&&!window.confirm("Discard unsaved research notes?"))return;const t=tasks[id],published=SPECIES_EDITORIAL[id];setSelected(id);setDraft(t?.draft??published?.summary??"");setNotes(t?.notes??"");setSources((t?.sources??published?.sources.map(s=>s.url)??[]).join("\n"));setStatus(t?.status==="reviewed"&&!canReview?"in_progress":t?.status??(published&&canReview?"reviewed":"in_progress"));setDirty(false);setMessage("");}
 async function save(e:FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);setError("");setMessage("");try{if(preview){setMessage("Preview only. No research was saved.");return;}const urls=sources.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const r=await backend().rpc("isitusa_save_editorial",{species:selected,expected_version:tasks[selected]?.version??null,next_status:status,next_draft:draft,next_notes:notes,next_sources:urls});if(r.error)throw new Error(r.error.message);setTasks(t=>({...t,[selected]:{species_id:selected,status,draft,notes,sources:urls,version:r.data,updated_at:new Date().toISOString()}}));setDirty(false);setMessage("Research saved to this private queue. Website descriptions are published separately after review.");}catch(e){setError(e instanceof Error?e.message:"Could not save. Your notes are still here.");}finally{setBusy(false);}}
 return <section><div className={admin.chatIntro}><BookOpenCheck size={26}/><div><h3>Species research, one useful profile at a time.</h3><p>{queue.length.toLocaleString()} species, alphabetically arranged in {Math.ceil(queue.length/50)} batches of up to 50. This tracks profile writing, separately from county evidence research.</p></div></div>
 <dl className={admin.usageTotals}>{Object.entries(states).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{loading?"—":totals[key]}</dd></div>)}</dl>
 <div className={admin.toolbar}><label><Search size={15} aria-hidden="true"/> Find a species<input className={styles.input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search all 2,504 species"/></label><label>Batch<select className={styles.select} value={batch} disabled={Boolean(query)} onChange={e=>setBatch(Number(e.target.value))}>{Array.from({length:Math.ceil(queue.length/50)},(_,i)=><option value={i+1} key={i}>Batch {i+1} · {i*50+1}–{Math.min((i+1)*50,queue.length)}</option>)}</select></label><label>Status<select className={styles.select} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{Object.entries(states).map(([s,l])=><option key={s} value={s}>{l}</option>)}</select></label></div>
 {error&&<Notice error>{error}</Notice>}{loading?<p role="status">Reading saved research...</p>:<div className={species?admin.split:undefined}><div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Species</th><th>Profile research</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} aria-selected={selected===row.id}><td><button onClick={()=>open(row.id)}>{row.commonName}</button><div className={styles.hint}><i>{row.scientificName}</i> · #{row.order}</div></td><td><span className={admin.pill}>{states[stateFor(row.id) as keyof typeof states]}</span></td></tr>)}</tbody></table>{!rows.length&&<p className={admin.empty}>No matching species.</p>}</div>{species&&<form className={`${admin.detail} ${styles.form}`} onSubmit={save}><h3>{species.commonName}</h3><a className="text-link" href={`/species/${species.id}`} target="_blank" rel="noopener noreferrer">Open existing profile <ArrowUpRight size={14}/></a><p className={styles.hint}>{SPECIES_EDITORIAL[species.id]?`Published editorial last reviewed ${SPECIES_EDITORIAL[species.id].reviewedAt}.`:"The current catalog profile has no separately reviewed editorial description yet."}</p><label className={styles.field}>Research status<select className={styles.select} value={status} onChange={e=>{setStatus(e.target.value);setDirty(true);}} disabled={busy}>{Object.entries(states).map(([s,l])=><option key={s} value={s} disabled={s==="reviewed"&&!canReview}>{l}</option>)}</select></label><label className={styles.field}>Description draft<textarea className={styles.textarea} rows={7} maxLength={6000} value={draft} onChange={e=>{setDraft(e.target.value);setDirty(true);}} disabled={busy}/></label><label className={styles.field}>Source URLs · one per line<textarea className={styles.textarea} rows={3} value={sources} onChange={e=>{setSources(e.target.value);setDirty(true);}} disabled={busy}/></label><label className={styles.field}>Research notes and remaining questions<textarea className={styles.textarea} rows={4} maxLength={6000} value={notes} onChange={e=>{setNotes(e.target.value);setDirty(true);}} disabled={busy}/></label><button className={styles.button} disabled={busy||preview}><Save size={16}/>{busy?"Saving...":"Save research"}</button>{message&&<Notice success>{message}</Notice>}</form>}</div>}
 </section>;
}
