"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { backend, configured } from "@/lib/participation/client";
import { Notice, styles } from "@/components/participation/shared";
import { ArrowLeft, ClipboardList, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import admin from "./admin.module.css";
export function StaffAuth({onReady}:{onReady:(session:Session)=>void}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[session,setSession]=useState<Session|null>(null),[factor,setFactor]=useState(""),[qr,setQr]=useState(""),[secret,setSecret]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const inspect=useCallback(async(next:Session)=>{setSession(next);const client=backend();const result=await client.auth.mfa.getAuthenticatorAssuranceLevel();if(result.error)throw result.error;if(result.data.currentLevel==="aal2"){onReady(next);return;}const list=await client.auth.mfa.listFactors();if(list.error)throw list.error;setFactor(list.data.totp.find(f=>f.status==="verified")?.id??"");},[onReady]);
 useEffect(()=>{if(!configured)return;let active=true;backend().auth.getSession().then(({data})=>{if(active&&data.session)void inspect(data.session).catch(()=>setError("Sign in again to continue."));});return()=>{active=false;};},[inspect]);
 async function login(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const result=await backend().auth.signInWithPassword({email,password});setPassword("");if(result.error||!result.data.session)throw new Error("Check your email and password.");const account=await backend().from("isitusa_staff").select("user_id").eq("user_id",result.data.session.user.id).eq("active",true).maybeSingle();if(account.error||!account.data){await backend().auth.signOut();throw new Error("This account does not have team access.");}await inspect(result.data.session);}catch(err){setError(err instanceof Error?err.message:"Sign-in failed.");}finally{setBusy(false);}}
 async function enroll(){setError("");setBusy(true);try{const result=await backend().auth.mfa.enroll({factorType:"totp",friendlyName:"IsItUSA team",issuer:"IsItUSA"});if(result.error)throw result.error;setFactor(result.data.id);setQr(result.data.totp.qr_code);setSecret(result.data.totp.secret);}catch{setError("Authenticator setup could not start. Please try again.");}finally{setBusy(false);}}
 async function verify(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const result=await backend().auth.mfa.challengeAndVerify({factorId:factor,code});if(result.error)throw result.error;const current=await backend().auth.getSession();if(!current.data.session)throw new Error();setCode("");setQr("");setSecret("");onReady(current.data.session);}catch{setError("That code did not work. Try the current code from your authenticator.");}finally{setBusy(false);}}
 async function reset(){setBusy(true);setError("");try{if(!email.trim())throw new Error("Enter your email address first.");const result=await backend().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth/confirm`});if(result.error)throw result.error;setMessage("If this address has an account, a recovery link will arrive shortly.");}catch{setError("We couldn't request a recovery email. Check the address and try again.");}finally{setBusy(false);}}
 return <div className={admin.authLayout}><div className={admin.authIntro}><h1>Good work starts with care.</h1><p>A private space for the people researching, reviewing and supporting the atlas.</p><ul><li><ClipboardList size={18} aria-hidden="true"/>Give every observation a thoughtful review.</li><li><Mail size={18} aria-hidden="true"/>Keep the community informed.</li><li><ShieldCheck size={18} aria-hidden="true"/>Keep private information in trusted hands.</li></ul><Link className="text-link" href="/"><ArrowLeft size={16} aria-hidden="true"/>Back to the atlas</Link></div><section className={admin.login}><h2>{session?"Verify your access":"Welcome to the team."}</h2><p>{session?"Use your authenticator to continue to the workspace.":"Sign in with your invited email address."}</p>{!configured&&<Notice>Team sign-in is being configured.</Notice>}{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 {!session?<form className={styles.form} onSubmit={login}><label className={styles.field}>Email<input className={styles.input} type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required disabled={!configured||busy}/></label><label className={styles.field}>Password<input className={styles.input} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required disabled={!configured||busy}/></label><button className={styles.button} disabled={!configured||busy}>{busy?"Signing in...":"Sign in"}</button><button type="button" onClick={()=>void reset()} className="text-link" disabled={!configured||busy}>Forgot your password?</button></form>:
 <div className={styles.form}>{!factor?<><p>Add an authenticator app to protect your access to private records.</p><button className={styles.button} onClick={()=>void enroll()} disabled={busy}>Set up authenticator</button></>:<form className={styles.form} onSubmit={verify}>{qr&&<><img width={220} height={220} src={qr.startsWith("data:image/svg+xml")?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`} alt="Scan this QR code with your authenticator app"/><details><summary>Enter a setup key instead</summary><code style={{overflowWrap:"anywhere"}}>{secret}</code></details></>}<label className={styles.field}>Authenticator code<input className={styles.input} value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required/></label><button className={styles.button} disabled={busy}>Verify and continue</button></form>}<button className="text-link" onClick={()=>{void backend().auth.signOut();setSession(null);setFactor("");setQr("");setSecret("");}}>Use a different account</button></div>}<div className={admin.loginFooter}><LockKeyhole size={15} aria-hidden="true"/><span>Invitation-only access. An authenticator protects private project records.</span></div></section></div>;
}
