"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { backend, configured } from "@/lib/participation/client";
import { Notice, styles } from "@/components/participation/shared";
import { ArrowLeft, ClipboardList, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import admin from "./admin.module.css";
import { AccountFrame } from "./account-frame";
import { setupRoleDescription } from "@/lib/participation/account-setup";
export function StaffAuth({onReady,onboarding=false,client:makeClient=backend}:{onReady:(session:Session)=>void;onboarding?:boolean;client?:typeof backend}){
 const available=makeClient!==backend||configured;
 const [checking,setChecking]=useState(true),[roleDescription,setRoleDescription]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[session,setSession]=useState<Session|null>(null),[factor,setFactor]=useState(""),[qr,setQr]=useState(""),[secret,setSecret]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const inspect=useCallback(async(next:Session)=>{const client=makeClient();const account=await client.from("isitusa_staff").select("is_owner,permissions").eq("user_id",next.user.id).eq("active",true).maybeSingle();if(account.error||!account.data){await client.auth.signOut();throw new Error("This account does not have active team access. Contact the workspace owner.");}setRoleDescription(setupRoleDescription(account.data));setSession(next);const result=await client.auth.mfa.getAuthenticatorAssuranceLevel();if(result.error)throw result.error;if(result.data.currentLevel==="aal2"){onReady(next);return;}const list=await client.auth.mfa.listFactors();if(list.error)throw list.error;setFactor(list.data.totp.find(f=>f.status==="verified")?.id??"");},[onReady,makeClient]);
 useEffect(()=>{if(!available){setChecking(false);return;}let active=true;void (async()=>{try{const {data,error}=await makeClient().auth.getSession();if(error)throw error;if(active&&data.session)await inspect(data.session);}catch(err){if(active)setError(err instanceof Error?err.message:"Sign in again to continue.");}finally{if(active)setChecking(false);}})();return()=>{active=false;};},[inspect,makeClient,available]);
 async function login(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const result=await makeClient().auth.signInWithPassword({email,password});setPassword("");if(result.error||!result.data.session)throw new Error("Check your email and password.");const account=await makeClient().from("isitusa_staff").select("user_id").eq("user_id",result.data.session.user.id).eq("active",true).maybeSingle();if(account.error||!account.data){await makeClient().auth.signOut();throw new Error("This account does not have team access.");}await inspect(result.data.session);}catch(err){setError(err instanceof Error?err.message:"Sign-in failed.");}finally{setBusy(false);}}
 async function enroll(){setError("");setBusy(true);try{const client=makeClient();const pending=await client.auth.mfa.listFactors();if(pending.error)throw pending.error;for(const item of pending.data.all.filter(f=>f.factor_type==="totp"&&f.status==="unverified")){const removed=await client.auth.mfa.unenroll({factorId:item.id});if(removed.error)throw removed.error;}const result=await client.auth.mfa.enroll({factorType:"totp",friendlyName:"IsItUSA team",issuer:"IsItUSA"});if(result.error)throw result.error;setFactor(result.data.id);setQr(result.data.totp.qr_code);setSecret(result.data.totp.secret);}catch{setError("Authenticator setup could not start. Try again, or sign out and return with your new password.");}finally{setBusy(false);}}
 async function verify(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const result=await makeClient().auth.mfa.challengeAndVerify({factorId:factor,code});if(result.error)throw result.error;const current=await makeClient().auth.getSession();if(!current.data.session)throw new Error();setCode("");setQr("");setSecret("");await inspect(current.data.session);}catch{setError("That code did not work. Try the current code from your authenticator.");}finally{setBusy(false);}}
 async function reset(){setBusy(true);setError("");try{if(!email.trim())throw new Error("Enter your email address first.");const result=await makeClient().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth/confirm`});if(result.error)throw result.error;setMessage("If this address has an account, a recovery link will arrive shortly.");}catch{setError("We couldn't request a recovery email. Check the address and try again.");}finally{setBusy(false);}}
 if(checking)return <AccountFrame title="Checking your account…" description="We’re finding the next step for your account."><p role="status">Please wait a moment.</p></AccountFrame>;
 if(session)return <AccountFrame step={onboarding?2:undefined} title={qr?"Connect your authenticator.":factor?"Verify your sign-in.":"Protect your account."} description={qr?"Add Isitusa to your authenticator app, then enter its six-digit code below.":factor?"Enter the current six-digit code from your authenticator app.":"An authenticator adds a second check before anyone can open private project records."}>
 {onboarding&&<p className={admin.savedPassword}><ShieldCheck size={17} aria-hidden="true"/>Password saved. One security step remains.</p>}
 {roleDescription&&<p className={admin.roleDescription}>{roleDescription}</p>}
 {error&&<Notice error>{error}</Notice>}
 {!factor?<div className={styles.form}><p className={styles.hint}>Use an authenticator app such as Apple Passwords, Google Authenticator, or 2FAS. On the same phone, you can enter a setup key instead of scanning a QR code.</p><button className={styles.button} onClick={()=>void enroll()} disabled={busy}>{busy?"Preparing setup…":"Set up authenticator"}</button></div>:<form className={styles.form} onSubmit={verify} aria-busy={busy}>
  {/* eslint-disable-next-line @next/next/no-img-element -- Local authenticator QR data must stay in the browser; do not send it to an image optimizer. */}
 {qr&&<div className={admin.authenticatorSetup}><div className={admin.qrCode}><img width={200} height={200} src={qr.startsWith("data:image/svg+xml")?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`} alt="Isitusa authenticator setup QR code"/></div><div><p>In your authenticator, choose <strong>Add account</strong> and scan this code.</p><details className={admin.setupKey}><summary>On this phone? Use the setup key</summary><p>Choose a time-based account, name it Isitusa, and enter this key. Keep it private.</p><code>{secret}</code></details></div></div>}
 <label className={styles.field}>Six-digit authenticator code<input className={`${styles.input} ${admin.codeInput}`} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required disabled={busy}/></label>
 <button className={styles.button} disabled={busy}>{busy?"Verifying…":"Verify and open workspace"}</button></form>}
 <button className={admin.accountSecondary} disabled={busy} onClick={()=>{void makeClient().auth.signOut().then(({error:signOutError})=>{if(signOutError){setError("Could not sign out. Please try again.");return;}setSession(null);setFactor("");setQr("");setSecret("");setCode("");setError("");});}}>Sign out and finish later</button>
 </AccountFrame>;
 return <div className={admin.authLayout}><div className={admin.authIntro}><h1>Good work starts with care.</h1><p>A private space for the people researching, reviewing and supporting the atlas.</p><ul><li><ClipboardList size={18} aria-hidden="true"/>Give every observation a thoughtful review.</li><li><Mail size={18} aria-hidden="true"/>Keep the community informed.</li><li><ShieldCheck size={18} aria-hidden="true"/>Keep private information in trusted hands.</li></ul><Link className="text-link" href="https://isitusa.com/"><ArrowLeft size={16} aria-hidden="true"/>Back to the atlas</Link></div><section className={admin.login}><h2>Welcome to the team.</h2><p>Sign in with your invited email address. If you paused during setup, we’ll help you finish.</p>{!available&&<Notice>Team sign-in is being configured.</Notice>}{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 <form className={styles.form} onSubmit={login}><label className={styles.field}>Email<input className={styles.input} type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required disabled={!available||busy}/></label><label className={styles.field}>Password<input className={styles.input} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required disabled={!available||busy}/></label><button className={styles.button} disabled={!available||busy}>{busy?"Signing in…":"Sign in"}</button><button type="button" onClick={()=>void reset()} className="text-link" disabled={!available||busy}>Send a password reset email</button></form><div className={admin.loginFooter}><LockKeyhole size={15} aria-hidden="true"/><span>Invitation-only access. An authenticator protects private project records.</span></div></section></div>;
}
