"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { Search, X } from "lucide-react";
import { WorkspaceFrame, WorkspaceOverview, WorkspaceLoading, type WorkspaceTab } from "./workspace-frame";
import { Connections } from "./connections";
import { AuditTrail } from "./audit-trail";
import { backend, request } from "@/lib/participation/client";
import { displayAmount, PERMISSIONS, ROLE_PRESETS, STATE_LABELS, type Contribution, type Permission, type Sighting, type Staff, type Subscriber } from "@/lib/participation/contracts";
import { CatalogPicker, Notice, styles } from "@/components/participation/shared";
import type { CatalogItem } from "@/lib/participation/contracts";
import { StaffAuth } from "./staff-auth";
import { SiteUsage } from "./site-usage";
import { CampaignDrafts } from "./campaign-drafts";
import admin from "./admin.module.css";

type Tab = WorkspaceTab;
type Review={id:number;previous_status:string;next_status:string;reason:string;created_at:string;matched_species_id:string|null};
type Adjustment={provider_event:string;payment_reference:string;kind:string;amount_minor:string;currency:string;created_at:string};
const date=(value:string)=>new Date(value).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"});
export function Workspace(){
 const requestSequence=useRef(0),draftDirty=useRef(false);
 const setDraftDirty=useCallback((value:boolean)=>{draftDirty.current=value;},[]);
 const [session,setSession]=useState<Session|null>(null),[me,setMe]=useState<Staff|null>(null),[tab,setTab]=useState<Tab>("overview"),[rows,setRows]=useState<unknown[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[page,setPage]=useState(0),[more,setMore]=useState(false),[counts,setCounts]=useState<Record<string,number>>({}),[selected,setSelected]=useState<Sighting|null>(null),[adjustments,setAdjustments]=useState<Adjustment[]>([]);
 const [search,setSearch]=useState(""),[searchInput,setSearchInput]=useState(""),[filter,setFilter]=useState("all"),[refreshedAt,setRefreshedAt]=useState<string|null>(null),[dataRevision,setDataRevision]=useState(0);
 const can=useCallback((permission:Permission)=>Boolean(me?.is_owner||me?.permissions.includes(permission)),[me]);
 const authenticated=Boolean(session),sessionUserId=session?.user.id,accessToken=session?.access_token;
 useEffect(()=>{if(!authenticated)return;const {data}=backend().auth.onAuthStateChange((event,next)=>{if(event==="SIGNED_OUT"){requestSequence.current++;setSession(null);setMe(null);setRows([]);setSelected(null);setCounts({});setAdjustments([]);setRefreshedAt(null);}else if(next)setSession(next);});return()=>data.subscription.unsubscribe();},[authenticated]);
 const refresh=useCallback(async()=>{
  if(!sessionUserId||!accessToken)return;const requestId=++requestSequence.current;setLoading(true);setError("");setRows([]);setSelected(null);setCounts({});setAdjustments([]);setMore(false);
  try{
   const client=backend(),who=await client.from("isitusa_staff").select("*").eq("user_id",sessionUserId).eq("active",true).maybeSingle();
   if(who.error||!who.data){if(requestId===requestSequence.current)setMe(null);throw new Error("Team access is unavailable. Contact the workspace owner.");}
   if(requestId!==requestSequence.current)return;const person=who.data as Staff;setMe(person);
   const allowed=(p:Permission)=>person.is_owner||person.permissions.includes(p);
   if(tab==="settings"){if(!allowed("team"))throw new Error("You do not have access to connections.");return;}
   if(tab==="overview"){
    const totals:Record<string,number>={};
    for(const [permission,table] of [["review","isitusa_sightings"],["audience","isitusa_subscribers"],["finance","isitusa_contributions"]] as const){
     if(!allowed(permission))continue;
     const check=await client.rpc("isitusa_can",{requested:permission});if(check.error||!check.data)throw new Error("Verify your authenticator or ask the owner to check your access.");
     const result=await client.from(table).select("id",{count:"exact",head:true});
     if(result.error)throw result.error;totals[permission]=result.count??0;
    }
    if(allowed("review")){const pending=await client.from("isitusa_sightings").select("id",{count:"exact",head:true}).in("status",["submitted","in_review"]);if(pending.error)throw pending.error;totals.pending=pending.count??0;}
    if(allowed("audience")){const confirmed=await client.from("isitusa_subscribers").select("id",{count:"exact",head:true}).not("confirmed_at","is",null).is("suppressed_at",null);if(confirmed.error)throw confirmed.error;totals.confirmed=confirmed.count??0;}
    if(requestId===requestSequence.current)setCounts(totals);return;
   }
   if(tab==="analytics"){if(!allowed("analytics"))throw new Error("You do not have access to site activity.");return;}
   const permission=tab as "review"|"audience"|"finance"|"team";if(!allowed(permission))throw new Error("You do not have access to this section.");
   const auth=await client.rpc("isitusa_can",{requested:permission});if(auth.error||!auth.data)throw new Error("Your session or access changed. Sign in again.");
   const table={review:"isitusa_sightings",audience:"isitusa_subscribers",finance:"isitusa_contribution_records",team:"isitusa_staff"}[permission];
   let query=client.from(table).select("*").order("created_at",{ascending:false}).order(tab==="team"?"user_id":"id",{ascending:false});
   const safe=search.replace(/[\\%_]/g,"").trim();
   if(safe)query=query.ilike({review:"species_label",audience:"email",finance:"provider_reference",team:"display_name"}[permission],`%${safe}%`);
   if(tab==="review"&&["submitted","in_review","needs_info","accepted","rejected"].includes(filter))query=query.eq("status",filter);
   if(tab==="audience"){if(filter==="confirmed")query=query.not("confirmed_at","is",null).is("suppressed_at",null);if(filter==="pending")query=query.is("confirmed_at",null).is("suppressed_at",null);if(filter==="suppressed")query=query.not("suppressed_at","is",null);}
   if(tab==="finance"&&["stripe","crypto"].includes(filter))query=query.eq("provider",filter);
   if(tab==="team"&&["active","revoked"].includes(filter))query=query.eq("active",filter==="active");
   const result=await query.range(page*25,page*25+25);
   if(result.error)throw result.error;if(requestId!==requestSequence.current)return;setRows(result.data.slice(0,25));setMore(result.data.length>25);
   if(tab==="finance"){const changes=await client.from("isitusa_payment_adjustments").select("*").order("created_at",{ascending:false}).limit(25);if(changes.error)throw changes.error;if(requestId===requestSequence.current)setAdjustments(changes.data);}
  }catch(err){if(requestId===requestSequence.current)setError(err instanceof Error?err.message:"This workspace could not load.");}finally{if(requestId===requestSequence.current){setLoading(false);setRefreshedAt(new Date().toISOString());setDataRevision(n=>n+1);}}
 },[sessionUserId,accessToken,tab,page,search,filter]);
 useEffect(()=>{const sequence=requestSequence;void refresh();return()=>{sequence.current++;};},[refresh]);
 if(!session)return <main id="main-content"><StaffAuth onReady={setSession}/></main>;
 const navigate=(next:Tab)=>{if(next===tab)return;if(draftDirty.current&&!window.confirm("Discard your unsaved draft changes?"))return;requestSequence.current++;setTab(next);setPage(0);setMessage("");setSearch("");setSearchInput("");setFilter("all");setSelected(null);setRows([]);setError("");};
 const filters:Record<string,[string,string][]>= {review:[["submitted","Submitted"],["in_review","In review"],["needs_info","More information"],["accepted","Accepted for research"],["rejected","Not accepted"]],audience:[["confirmed","Confirmed"],["pending","Awaiting confirmation"],["suppressed","Suppressed"]],finance:[["stripe","Stripe"],["crypto","Cryptocurrency"]],team:[["active","Active"],["revoked","Revoked"]]};
 return <WorkspaceFrame name={me?.display_name??"Team member"} owner={Boolean(me?.is_owner)} tab={tab} can={can} loading={loading} refreshedAt={refreshedAt} onTab={navigate} onRefresh={()=>void refresh()} onSignOut={()=>{if(!draftDirty.current||window.confirm("Discard your unsaved draft changes and sign out?"))void backend().auth.signOut();}}>
 {filters[tab]&&<form className={admin.toolbar} onSubmit={event=>{event.preventDefault();setPage(0);setSearch(searchInput.trim());}}><label>Search {tab==="review"?"observations":tab==="audience"?"email addresses":tab==="finance"?"references":"names"}<input className={styles.input} value={searchInput} onChange={event=>setSearchInput(event.target.value)} maxLength={100} autoComplete="off" placeholder={tab==="review"?"Species or observer identification":tab==="finance"?"Payment reference":"Search records"}/></label><label>Show<select className={styles.select} value={filter} onChange={event=>{setPage(0);setFilter(event.target.value);}}><option value="all">All records</option>{filters[tab].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className={`${styles.button} ${styles.secondary}`} type="submit"><Search size={16} aria-hidden="true"/>Search</button>{(search||filter!=="all")&&<button className="text-link" type="button" onClick={()=>{setSearch("");setSearchInput("");setFilter("all");setPage(0);}}>Clear</button>}</form>}
 {error&&<Notice error>{error}</Notice>}{message&&<Notice success>{message}</Notice>}{loading?<WorkspaceLoading/>:!error&&<>
 {tab==="analytics"&&<SiteUsage key={dataRevision} token={session.access_token}/>}
 {tab==="overview"&&<WorkspaceOverview counts={counts} can={can} onTab={navigate}/>}
 {tab==="review"&&<div className={selected?admin.split:undefined}><div>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Observation</th><th>Status</th></tr></thead><tbody>{(rows as Sighting[]).map(row=><tr key={row.id} aria-selected={selected?.id===row.id}><td><button aria-expanded={selected?.id===row.id} onClick={()=>setSelected(row)}>{row.species_label}</button><div className={styles.hint}>{row.county_id} / {date(row.observed_on+"T12:00:00Z")}</div></td><td><span className={admin.pill}>{STATE_LABELS[row.status]}</span></td></tr>)}</tbody></table></div>:<Empty text={search||filter!=="all"?"No observations match these filters.":"No sightings to review yet."}/>}</div>{selected&&<SightingReview key={selected.id} sighting={selected} onClose={()=>setSelected(null)} canDecide={can("review_decide")} session={session} onSaved={()=>{setMessage("Review saved.");void refresh();}}/>}</div>}
 {tab==="audience"&&<>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Email</th><th>Choices</th><th>Delivery status</th></tr></thead><tbody>{(rows as Subscriber[]).map(row=><tr key={row.id}><td>{row.email}<div className={styles.hint}>Added {date(row.created_at)}</div></td><td>{row.preferences.streams.map(stream=>({counties:"My counties",species:"Species I follow",facts:"Species stories",action:"Ways to help"}[stream])).join(", ")||"None confirmed"}<div className={styles.hint}>{row.preferences.counties.length} counties / {row.preferences.species.length} species</div></td><td>{row.suppressed_at?`Suppressed: ${row.suppression_reason}`:row.confirmed_at?"Confirmed":"Awaiting confirmation"}</td></tr>)}</tbody></table></div>:<Empty text={search||filter!=="all"?"No subscribers match these filters.":"No email signups yet."}/>}<p className={styles.hint} style={{marginTop:16}}>Only confirmed, unsuppressed choices are eligible for delivery. Staff cannot opt someone into a category on their behalf.</p></>}
 {tab==="finance"&&<>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Received</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{(rows as Contribution[]).map(row=><tr key={row.id}><td>{date(row.created_at)}<div className={styles.hint}>{row.provider} / {row.status}</div></td><td>{displayAmount(String(row.amount_minor),row.decimals,row.currency)}<div className={styles.hint}>{row.supporter_email??"No email supplied"}</div></td><td style={{overflowWrap:"anywhere",maxWidth:260}}>{row.provider_reference}<div className={styles.hint}>{row.verification_note}</div></td></tr>)}</tbody></table></div>:<Empty text={search||filter!=="all"?"No receipts match these filters.":"No contribution records have been imported yet."}/>}<p className={styles.hint} style={{marginTop:16}}>This ledger only shows records received by the reconciliation service. An empty ledger does not mean no donations were received. Amounts are gross receipts in their original currencies. Refund and dispute events below are separate snapshots, not additional donations or amounts to sum.</p>{adjustments.length>0&&<section className={styles.section}><h3>Refunds and disputes</h3><ul>{adjustments.map(a=><li key={a.provider_event} className={styles.notice}>{a.kind} / {displayAmount(String(a.amount_minor),2,a.currency)} / {a.payment_reference}</li>)}</ul></section>}<CryptoReceipt onSaved={()=>{setMessage("Verified receipt recorded.");void refresh();}}/>{me?.is_owner&&<WalletSetup onSaved={()=>setMessage("Receiving address saved. Refresh Connections to review it.")}/>}</>}
 {tab==="team"&&<><div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Team member</th><th>Access</th><th>Manage</th></tr></thead><tbody>{(rows as Staff[]).map(person=><TeamRow key={person.user_id} person={person} self={person.user_id===session.user.id} onSaved={()=>{setMessage("Team access updated.");void refresh();}}/>)}</tbody></table></div><TeamInvite session={session} onSaved={()=>{setMessage("Invitation sent.");void refresh();}}/><AuditTrail key={dataRevision}/></>}
 {tab==="settings"&&<Connections key={dataRevision} token={session.access_token}/>}
 {["review","audience","finance","team"].includes(tab)&&<div className={admin.pagination}><button className={`${styles.button} ${styles.secondary}`} disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span className={styles.hint}>Page {page+1}</span><button className={`${styles.button} ${styles.secondary}`} disabled={!more} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}{tab==="audience"&&me&&can("audience")&&<CampaignDrafts onDirtyChange={setDraftDirty} refreshSignal={dataRevision}/>}</WorkspaceFrame>;
}
function Empty({text}:{text:string}){return <div className={admin.empty}><strong>{text}</strong><p>Refresh to check again, or clear any active filters.</p></div>;}
function SightingReview({sighting,session,onSaved,canDecide,onClose}:{sighting:Sighting;session:Session;onSaved:()=>void;canDecide:boolean;onClose:()=>void}){
 const [match,setMatch]=useState<CatalogItem[]>(sighting.matched_species_id?[{id:sighting.matched_species_id,label:sighting.matched_species_id.replaceAll("-"," ")}]:[]);
 const [status,setStatus]=useState("in_review"),[reason,setReason]=useState(""),[history,setHistory]=useState<Review[]>([]),[photos,setPhotos]=useState<{path:string;url?:string}[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;Promise.all([backend().from("isitusa_reviews").select("*").eq("sighting_id",sighting.id).order("created_at",{ascending:false}),backend().from("isitusa_assets").select("path").eq("sighting_id",sighting.id)]).then(([reviews,assets])=>{if(!current)return;if(reviews.error||assets.error){setError("The full review history could not load.");return;}setHistory(reviews.data);setPhotos(assets.data);});return()=>{current=false;};},[sighting.id]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const result=await backend().rpc("isitusa_review_identification",{sighting:sighting.id,expected_version:sighting.version,next_status:status,reason,species:match[0]?.id??null});if(result.error)throw result.error;onSaved();}catch(err){setError(err instanceof Error?err.message:"The review could not be saved. Refresh and try again.");}finally{setBusy(false);}}
 async function photo(path:string){try{const result=await request<{url:string}>("photo",{path},session.access_token);setPhotos(items=>items.map(p=>p.path===path?{...p,url:result.url}:p));}catch{setError("The photograph could not open. Refresh your access and try again.");}}
 return <article className={admin.detail}><div className={admin.detailClose}><button onClick={onClose}><X size={16} aria-hidden="true"/>Close observation</button></div><h3>{sighting.species_label}</h3><dl><dt>Observed</dt><dd>{date(sighting.observed_on+"T12:00:00Z")}</dd><dt>County</dt><dd>{sighting.county_id}</dd><dt>Location</dt><dd>{sighting.location_note}{sighting.latitude!==null&&<div>{sighting.latitude}, {sighting.longitude}</div>}</dd><dt>Contact</dt><dd>{sighting.contact_email??"Not supplied"}</dd><dt>Notes</dt><dd>{sighting.notes||"None supplied"}</dd><dt>Received</dt><dd>{date(sighting.created_at)}</dd></dl>
 {photos.map((p,i)=><div key={p.path}>{p.url?<img className={admin.photo} src={p.url} alt={`Private observation photograph ${i+1}`}/>:<button className={`${styles.button} ${styles.secondary}`} onClick={()=>void photo(p.path)}>Open photograph {i+1}</button>}</div>)}
 <section className={styles.section}><h4>Compare the identification</h4><p className={styles.hint}>Match the observation to a catalog species, then compare its identifying features and photographs. Keep the observer&apos;s original description above as evidence.</p><CatalogPicker kind="species" max={1} value={match} onChange={setMatch}/>{match[0]&&<a href={`/species/${encodeURIComponent(match[0].id)}`} target="_blank" rel="noopener noreferrer" className="text-link">Open species reference in a new tab</a>}<p className={styles.hint}>Only a lead reviewer can accept an identified observation. Acceptance queues it for research review; it does not change the public map.</p></section>
 {error&&<Notice error>{error}</Notice>}<form className={styles.form} onSubmit={save}><label className={styles.field}>Review decision<select value={status} onChange={e=>setStatus(e.target.value)} className={styles.select}>{(canDecide?["in_review","needs_info","accepted","rejected"]:["in_review","needs_info"]).map(s=><option value={s} key={s}>{STATE_LABELS[s as keyof typeof STATE_LABELS]}</option>)}</select></label><label className={styles.field}>Reason and supporting source<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={2000} required className={styles.textarea} placeholder="Explain the decision and include relevant source links."/></label><button className={styles.button} disabled={busy}>{busy?"Saving...":"Save review"}</button></form>
 <ol className={admin.timeline}>{history.map(event=><li key={event.id}><strong>{STATE_LABELS[event.next_status as keyof typeof STATE_LABELS]}</strong><p>{event.reason}</p>{event.matched_species_id&&<a className="text-link" href={`/species/${encodeURIComponent(event.matched_species_id)}`} target="_blank" rel="noopener noreferrer">Identification: {event.matched_species_id.replaceAll("-"," ")}</a>}<span className={styles.hint}>{date(event.created_at)}</span></li>)}</ol></article>;
}
function PermissionChoices({value,onChange}:{value:Permission[];onChange:(p:Permission[])=>void}){return <><label className={styles.field}>Start with a role<select className={styles.select} value="" onChange={e=>{const role=ROLE_PRESETS.find(r=>r.name===e.target.value);if(role)onChange([...role.permissions]);}}><option value="">Choose a role preset</option>{ROLE_PRESETS.map(role=><option key={role.name} value={role.name}>{role.name}</option>)}</select></label><div className={styles.row}>{PERMISSIONS.map(p=><label key={p} className={styles.row}><input type="checkbox" checked={value.includes(p)} onChange={e=>onChange(e.target.checked?[...value,p]:value.filter(v=>v!==p))}/>{p==="review"?"Review sightings":p==="audience"?"Email audience":p==="finance"?"Contributions":p==="analytics"?"Site activity":p==="review_decide"?"Final review decisions":"Manage team"}</label>)}</div><p className={styles.hint}>Only the owner can grant elevated permissions. Role presets can be adjusted before saving.</p></>;}
function TeamRow({person,self,onSaved}:{person:Staff;self:boolean;onSaved:()=>void}){
 const [editing,setEditing]=useState(false),[permissions,setPermissions]=useState(person.permissions),[enabled,setEnabled]=useState(person.active),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);setError("");const result=await backend().rpc("isitusa_save_staff",{target:person.user_id,grants:permissions,enabled,name:person.display_name});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 return <tr><td>{person.display_name}<div className={styles.hint}>{person.email}</div></td><td>{person.is_owner?"Owner":person.active?person.permissions.join(", "):"Access revoked"}{editing&&<><PermissionChoices value={permissions} onChange={setPermissions}/><label className={styles.row}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Account enabled</label></>}</td><td>{!person.is_owner&&!self&&<button disabled={busy} onClick={()=>editing?void save():setEditing(true)}>{editing?"Save access":"Edit access"}</button>}{editing&&<button disabled={busy} onClick={()=>{setEditing(false);setPermissions(person.permissions);setEnabled(person.active);setError("");}}>Cancel</button>}{error&&<p role="alert" className={styles.error}>{error}</p>}</td></tr>;
}
function TeamInvite({session,onSaved}:{session:Session;onSaved:()=>void}){
 const [permissions,setPermissions]=useState<Permission[]>(["review"]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError("");try{await request("invite",{email:data.get("email"),name:data.get("name"),permissions},session.access_token);onSaved();}catch(err){setError(err instanceof Error?err.message:"Invitation failed.");}finally{setBusy(false);}}
 return <section className={styles.section}><h2>Invite someone to help.</h2><form className={styles.form} onSubmit={invite}><div className={styles.grid}><label className={styles.field}>Name<input name="name" maxLength={100} required className={styles.input}/></label><label className={styles.field}>Email<input type="email" name="email" required className={styles.input}/></label></div><PermissionChoices value={permissions} onChange={setPermissions}/><p className={styles.hint}>Reviewers can access observations and their private evidence. Mailing lists, contributions, and team management require separate permissions.</p><button className={styles.button} disabled={busy}>{busy?"Sending invitation...":"Send invitation"}</button>{error&&<Notice error>{error}</Notice>}</form></section>;
}
function CryptoReceipt({onSaved}:{onSaved:()=>void}){
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(e.currentTarget));const result=await backend().rpc("isitusa_crypto_receipt",{asset:values.asset,reference:values.reference,atomic_amount:values.amount,note:values.note});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 return <details className={styles.section}><summary className="text-link">Record a verified crypto receipt</summary><form className={styles.form} onSubmit={save}><Notice>Record only a transfer verified in the receiving wallet. A transaction ID or a visitor&apos;s claim is not proof of receipt. Monero requires private wallet verification.</Notice><label className={styles.field}>Asset<select name="asset" className={styles.select}><option>BTC</option><option>XMR</option><option>ETH</option></select></label><label className={styles.field}>Unique transaction reference<input name="reference" required maxLength={180} className={styles.input}/></label><label className={styles.field}>Amount in the smallest unit<input name="amount" required pattern="[0-9]+" inputMode="numeric" className={styles.input}/><span className={styles.hint}>Satoshis for BTC, piconero for XMR, wei for ETH. Use the exact integer from your wallet.</span></label><label className={styles.field}>How was receipt verified?<textarea name="note" required minLength={10} maxLength={1000} className={styles.textarea}/></label><button disabled={busy} className={styles.button}>Record verified receipt</button>{error&&<Notice error>{error}</Notice>}</form></details>;
}
function WalletSetup({onSaved}:{onSaved:()=>void}){
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);const values=Object.fromEntries(new FormData(e.currentTarget));const result=await backend().rpc("isitusa_wallet",{asset:values.asset,address:values.address,note:values.note});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 return <details className={styles.section}><summary className="text-link">Set a verified receiving address</summary><form className={styles.form} onSubmit={save}><Notice>Public receiving addresses only. Verify ownership, checksum, and the full address in your own wallet before publishing. Never paste a seed phrase, private key, or Monero view key.</Notice><label className={styles.field}>Asset and network<select name="asset" className={styles.select}><option value="BTC">Bitcoin mainnet</option><option value="XMR">Monero mainnet</option><option value="ETH">Ethereum mainnet</option></select></label><label className={styles.field}>Receiving address<input name="address" required maxLength={120} className={styles.input} autoComplete="off"/></label><label className={styles.field}>Verification record<textarea name="note" minLength={10} maxLength={1000} required className={styles.textarea} placeholder="When and how you checked ownership, checksum, and network."/></label><label className={styles.choice}><input type="checkbox" required/><span>I verified this address in an isitusa-controlled wallet. Publishing replaces the active address for this asset.</span></label><button className={styles.button} disabled={busy}>Publish receiving address</button>{error&&<Notice error>{error}</Notice>}</form></details>;
}
