"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { ClipboardList, HeartHandshake, LayoutDashboard, LogOut, Mail, RefreshCw, Settings2, Users } from "lucide-react";
import { backend, request } from "@/lib/participation/client";
import { displayAmount, PERMISSIONS, STATE_LABELS, type Contribution, type Permission, type PublicConfig, type Sighting, type Staff, type Subscriber } from "@/lib/participation/contracts";
import { Notice, styles } from "@/components/participation/shared";
import { StaffAuth } from "./staff-auth";
import { CampaignDrafts } from "./campaign-drafts";
import admin from "./admin.module.css";

type Tab="overview"|"review"|"audience"|"finance"|"team"|"settings";
type Review={id:number;previous_status:string;next_status:string;reason:string;created_at:string};
type Adjustment={provider_event:string;payment_reference:string;kind:string;amount_minor:string;currency:string;created_at:string};
const tabs=[{id:"overview",name:"Overview",icon:LayoutDashboard},{id:"review",name:"Sightings",icon:ClipboardList},{id:"audience",name:"Email audience",icon:Mail},{id:"finance",name:"Contributions",icon:HeartHandshake},{id:"team",name:"Team access",icon:Users},{id:"settings",name:"Connections",icon:Settings2}] as const;
const date=(value:string)=>new Date(value).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"});
export function Workspace(){
 const requestSequence=useRef(0);
 const [session,setSession]=useState<Session|null>(null),[me,setMe]=useState<Staff|null>(null),[tab,setTab]=useState<Tab>("overview"),[rows,setRows]=useState<unknown[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[page,setPage]=useState(0),[more,setMore]=useState(false),[counts,setCounts]=useState<Record<string,number>>({}),[selected,setSelected]=useState<Sighting|null>(null),[config,setConfig]=useState<PublicConfig|null>(null),[adjustments,setAdjustments]=useState<Adjustment[]>([]);
 const can=useCallback((permission:Permission)=>Boolean(me?.is_owner||me?.permissions.includes(permission)),[me]);
 useEffect(()=>{if(!session)return;const {data}=backend().auth.onAuthStateChange((event,next)=>{if(event==="SIGNED_OUT"){setSession(null);setMe(null);setRows([]);setSelected(null);}else if(next)setSession(next);});return()=>data.subscription.unsubscribe();},[Boolean(session)]);
 const refresh=useCallback(async()=>{
  if(!session)return;const requestId=++requestSequence.current;setLoading(true);setError("");setRows([]);setSelected(null);setCounts({});setAdjustments([]);
  try{
   const client=backend(),who=await client.from("isitusa_staff").select("*").eq("user_id",session.user.id).eq("active",true).maybeSingle();
   if(who.error||!who.data)throw new Error("Team access is unavailable. Contact the workspace owner.");
   if(requestId!==requestSequence.current)return;const person=who.data as Staff;setMe(person);
   const allowed=(p:Permission)=>person.is_owner||person.permissions.includes(p);
   if(tab==="settings"){const nextConfig=await request<PublicConfig>("config");if(requestId===requestSequence.current)setConfig(nextConfig);return;}
   if(tab==="overview"){
    const totals:Record<string,number>={};
    for(const [permission,table] of [["review","isitusa_sightings"],["audience","isitusa_subscribers"],["finance","isitusa_contributions"]] as const){
     if(!allowed(permission))continue;
     const check=await client.rpc("isitusa_can",{requested:permission});if(check.error||!check.data)throw new Error("Verify your authenticator or ask the owner to check your access.");
     const result=await client.from(table).select("id",{count:"exact",head:true});
     if(result.error)throw result.error;totals[permission]=result.count??0;
    }
    if(requestId===requestSequence.current)setCounts(totals);return;
   }
   const permission=tab as Permission;if(!allowed(permission))throw new Error("You do not have access to this section.");
   const auth=await client.rpc("isitusa_can",{requested:permission});if(auth.error||!auth.data)throw new Error("Your session or access changed. Sign in again.");
   const table={review:"isitusa_sightings",audience:"isitusa_subscribers",finance:"isitusa_contribution_records",team:"isitusa_staff"}[permission];
   const result=await client.from(table).select("*").order("created_at",{ascending:false}).range(page*25,page*25+25);
   if(result.error)throw result.error;if(requestId!==requestSequence.current)return;setRows(result.data.slice(0,25));setMore(result.data.length>25);
   if(tab==="finance"){const changes=await client.from("isitusa_payment_adjustments").select("*").order("created_at",{ascending:false}).limit(25);if(changes.error)throw changes.error;if(requestId===requestSequence.current)setAdjustments(changes.data);}
  }catch(err){if(requestId===requestSequence.current)setError(err instanceof Error?err.message:"This workspace could not load.");}finally{if(requestId===requestSequence.current)setLoading(false);}
 },[session?.user.id,session?.access_token,tab,page]);
 useEffect(()=>{void refresh();return()=>{requestSequence.current++;};},[refresh]);
 if(!session)return <main id="main-content"><StaffAuth onReady={setSession}/></main>;
 return <main id="main-content" className={admin.shell}><header className={admin.top}><div><h1>IsItUSA workspace</h1><p className={admin.security}>{me?.display_name??"Team member"} · Private team access</p></div><button className={`${styles.button} ${styles.secondary}`} onClick={()=>void backend().auth.signOut()}><LogOut size={16}/>Sign out</button></header>
 <div className={admin.body}><nav className={admin.nav} aria-label="Workspace">{tabs.filter(item=>item.id==="overview"||item.id==="settings"||can(item.id)).map(item=><button key={item.id} aria-current={tab===item.id?"page":undefined} onClick={()=>{setTab(item.id);setPage(0);setMessage("");}}><item.icon size={18} aria-hidden="true"/>{item.name}</button>)}</nav>
 <section className={admin.panel}><div className={admin.heading}><h2>{tabs.find(item=>item.id===tab)?.name}</h2><button className={`${styles.button} ${styles.secondary}`} disabled={loading} onClick={()=>void refresh()}><RefreshCw size={16} aria-hidden="true"/>Refresh</button></div>
 {error&&<Notice error>{error}</Notice>}{message&&<Notice success>{message}</Notice>}{loading?<p role="status" className={admin.empty}>Loading your workspace...</p>:!error&&<>
 {tab==="overview"&&<><div className={admin.stats}>{Object.entries(counts).map(([key,value])=><div className={admin.stat} key={key}><span>{key==="review"?"Sightings received":key==="audience"?"Email records, including unconfirmed":"Verified contribution records"}</span><strong>{value.toLocaleString()}</strong></div>)}</div><Notice>Accepting a sighting records a review decision. It still needs evidence admission before it changes the public map.</Notice></>}
 {tab==="review"&&<div className={selected?admin.split:undefined}><div>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Observation</th><th>Status</th></tr></thead><tbody>{(rows as Sighting[]).map(row=><tr key={row.id}><td><button onClick={()=>setSelected(row)}>{row.species_label}</button><div className={styles.hint}>{row.county_id} · {date(row.observed_on+"T12:00:00Z")}</div></td><td><span className={admin.pill}>{STATE_LABELS[row.status]}</span></td></tr>)}</tbody></table></div>:<Empty text="No sightings to review yet."/>}</div>{selected&&<SightingReview key={selected.id} sighting={selected} session={session} onSaved={()=>{setMessage("Review saved.");void refresh();}}/>}</div>}
 {tab==="audience"&&<>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Email</th><th>Choices</th><th>Delivery status</th></tr></thead><tbody>{(rows as Subscriber[]).map(row=><tr key={row.id}><td>{row.email}<div className={styles.hint}>Added {date(row.created_at)}</div></td><td>{row.preferences.streams.join(", ")||"None confirmed"}<div className={styles.hint}>{row.preferences.counties.length} counties · {row.preferences.species.length} species</div></td><td>{row.suppressed_at?`Suppressed: ${row.suppression_reason}`:row.confirmed_at?"Confirmed":"Awaiting confirmation"}</td></tr>)}</tbody></table></div>:<Empty text="No email signups yet."/>}<p className={styles.hint} style={{marginTop:16}}>Only confirmed, unsuppressed choices are eligible for delivery. Staff cannot opt someone into a category on their behalf.</p><CampaignDrafts/></>}
 {tab==="finance"&&<>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Received</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{(rows as Contribution[]).map(row=><tr key={row.id}><td>{date(row.created_at)}<div className={styles.hint}>{row.provider} · {row.status}</div></td><td>{displayAmount(String(row.amount_minor),row.decimals,row.currency)}<div className={styles.hint}>{row.supporter_email??"No email supplied"}</div></td><td style={{overflowWrap:"anywhere",maxWidth:260}}>{row.provider_reference}<div className={styles.hint}>{row.verification_note}</div></td></tr>)}</tbody></table></div>:<Empty text="No verified contributions yet."/>}<p className={styles.hint} style={{marginTop:16}}>Amounts are gross receipts in their original currencies. Refund and dispute events below are separate snapshots, not additional donations or amounts to sum.</p>{adjustments.length>0&&<section className={styles.section}><h3>Refunds and disputes</h3><ul>{adjustments.map(a=><li key={a.provider_event} className={styles.notice}>{a.kind} · {displayAmount(String(a.amount_minor),2,a.currency)} · {a.payment_reference}</li>)}</ul></section>}<CryptoReceipt onSaved={()=>{setMessage("Verified receipt recorded.");void refresh();}}/>{me?.is_owner&&<WalletSetup onSaved={()=>setMessage("Receiving address saved. Refresh Connections to review it.")}/>}</>}
 {tab==="team"&&<><div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Team member</th><th>Access</th><th>Manage</th></tr></thead><tbody>{(rows as Staff[]).map(person=><TeamRow key={person.user_id} person={person} self={person.user_id===session.user.id} onSaved={()=>{setMessage("Team access updated.");void refresh();}}/>)}</tbody></table></div><TeamInvite session={session} onSaved={()=>{setMessage("Invitation sent.");void refresh();}}/></>}
 {tab==="settings"&&<><div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Service</th><th>Status</th></tr></thead><tbody><tr><td>Private workspace</td><td>Signed in with an authenticator</td></tr><tr><td>Resend email</td><td>{config?.email?"Enabled":"Setup pending"}</td></tr><tr><td>Sighting intake</td><td>{config?.reports?"Enabled":"Setup pending"}</td></tr><tr><td>Stripe checkout</td><td>{config?.payments?"Enabled":"Setup pending"}</td></tr><tr><td>Crypto receiving addresses</td><td>{config?.wallets.length??0} verified and active</td></tr><tr><td>Klaviyo</td><td>Not connected</td></tr></tbody></table></div><p className={styles.hint} style={{marginTop:16}}>Provider credentials and service activation are managed outside this workspace. No secrets are displayed here.</p></>}
 {["review","audience","finance","team"].includes(tab)&&<div className={styles.row} style={{marginTop:20}}><button className={`${styles.button} ${styles.secondary}`} disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span className={styles.hint}>Page {page+1}</span><button className={`${styles.button} ${styles.secondary}`} disabled={!more} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}</section></div></main>;
}
function Empty({text}:{text:string}){return <div className={admin.empty}>{text}</div>;}
function SightingReview({sighting,session,onSaved}:{sighting:Sighting;session:Session;onSaved:()=>void}){
 const [status,setStatus]=useState("in_review"),[reason,setReason]=useState(""),[history,setHistory]=useState<Review[]>([]),[photos,setPhotos]=useState<{path:string;url?:string}[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;Promise.all([backend().from("isitusa_reviews").select("*").eq("sighting_id",sighting.id).order("created_at",{ascending:false}),backend().from("isitusa_assets").select("path").eq("sighting_id",sighting.id)]).then(([reviews,assets])=>{if(!current)return;if(reviews.error||assets.error){setError("The full review history could not load.");return;}setHistory(reviews.data);setPhotos(assets.data);});return()=>{current=false;};},[sighting.id]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");const result=await backend().rpc("isitusa_review",{sighting:sighting.id,expected_version:sighting.version,next_status:status,reason});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 async function photo(path:string){try{const result=await request<{url:string}>("photo",{path},session.access_token);setPhotos(items=>items.map(p=>p.path===path?{...p,url:result.url}:p));}catch{setError("The photograph could not open. Refresh your access and try again.");}}
 return <article className={admin.detail}><h3>{sighting.species_label}</h3><dl><dt>Observed</dt><dd>{date(sighting.observed_on+"T12:00:00Z")}</dd><dt>County</dt><dd>{sighting.county_id}</dd><dt>Location</dt><dd>{sighting.location_note}{sighting.latitude!==null&&<div>{sighting.latitude}, {sighting.longitude}</div>}</dd><dt>Contact</dt><dd>{sighting.contact_email??"Not supplied"}</dd><dt>Notes</dt><dd>{sighting.notes||"None supplied"}</dd><dt>Received</dt><dd>{date(sighting.created_at)}</dd></dl>
 {photos.map((p,i)=><div key={p.path}>{p.url?<img className={admin.photo} src={p.url} alt={`Private observation photograph ${i+1}`}/>:<button className={`${styles.button} ${styles.secondary}`} onClick={()=>void photo(p.path)}>Open photograph {i+1}</button>}</div>)}
 {error&&<Notice error>{error}</Notice>}<form className={styles.form} onSubmit={save}><label className={styles.field}>Review decision<select value={status} onChange={e=>setStatus(e.target.value)} className={styles.select}>{["in_review","needs_info","accepted","rejected"].map(s=><option value={s} key={s}>{STATE_LABELS[s as keyof typeof STATE_LABELS]}</option>)}</select></label><label className={styles.field}>Reason and supporting source<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={2000} required className={styles.textarea} placeholder="Explain the decision and include relevant source links."/></label><button className={styles.button} disabled={busy}>{busy?"Saving...":"Save review"}</button></form>
 <ol className={admin.timeline}>{history.map(event=><li key={event.id}><strong>{STATE_LABELS[event.next_status as keyof typeof STATE_LABELS]}</strong><p>{event.reason}</p><span className={styles.hint}>{date(event.created_at)}</span></li>)}</ol></article>;
}
function PermissionChoices({value,onChange}:{value:Permission[];onChange:(p:Permission[])=>void}){return <div className={styles.row}>{PERMISSIONS.map(p=><label key={p} className={styles.row}><input type="checkbox" checked={value.includes(p)} onChange={e=>onChange(e.target.checked?[...value,p]:value.filter(v=>v!==p))}/>{p==="review"?"Review sightings":p==="audience"?"Email audience":p==="finance"?"Contributions":"Manage team"}</label>)}</div>;}
function TeamRow({person,self,onSaved}:{person:Staff;self:boolean;onSaved:()=>void}){
 const [editing,setEditing]=useState(false),[permissions,setPermissions]=useState(person.permissions),[enabled,setEnabled]=useState(person.active),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);const result=await backend().rpc("isitusa_save_staff",{target:person.user_id,grants:permissions,enabled,name:person.display_name});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 return <tr><td>{person.display_name}<div className={styles.hint}>{person.email}</div></td><td>{person.is_owner?"Owner":person.active?person.permissions.join(", "):"Access revoked"}{editing&&<><PermissionChoices value={permissions} onChange={setPermissions}/><label className={styles.row}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Account enabled</label></>}</td><td>{!person.is_owner&&!self&&<button disabled={busy} onClick={()=>editing?void save():setEditing(true)}>{editing?"Save access":"Edit access"}</button>}{error&&<p role="alert" className={styles.error}>{error}</p>}</td></tr>;
}
function TeamInvite({session,onSaved}:{session:Session;onSaved:()=>void}){
 const [permissions,setPermissions]=useState<Permission[]>(["review"]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError("");try{await request("invite",{email:data.get("email"),name:data.get("name"),permissions},session.access_token);onSaved();}catch(err){setError(err instanceof Error?err.message:"Invitation failed.");}finally{setBusy(false);}}
 return <section className={styles.section}><h2>Invite someone to help.</h2><form className={styles.form} onSubmit={invite}><div className={styles.grid}><label className={styles.field}>Name<input name="name" maxLength={100} required className={styles.input}/></label><label className={styles.field}>Email<input type="email" name="email" required className={styles.input}/></label></div><PermissionChoices value={permissions} onChange={setPermissions}/><p className={styles.hint}>Reviewers can access observations and their private evidence. Mailing lists, contributions, and team management require separate permissions.</p><button className={styles.button} disabled={busy}>{busy?"Sending invitation...":"Send invitation"}</button>{error&&<Notice error>{error}</Notice>}</form></section>;
}
function CryptoReceipt({onSaved}:{onSaved:()=>void}){
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(e.currentTarget));const result=await backend().rpc("isitusa_crypto_receipt",{asset:values.asset,reference:values.reference,atomic_amount:values.amount,note:values.note});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 return <details className={styles.section}><summary className="text-link">Record a verified crypto receipt</summary><form className={styles.form} onSubmit={save}><Notice>Record only a transfer verified in the receiving wallet. A transaction ID or a visitor's claim is not proof of receipt. Monero requires private wallet verification.</Notice><label className={styles.field}>Asset<select name="asset" className={styles.select}><option>BTC</option><option>XMR</option><option>ETH</option></select></label><label className={styles.field}>Unique transaction reference<input name="reference" required maxLength={180} className={styles.input}/></label><label className={styles.field}>Amount in the smallest unit<input name="amount" required pattern="[0-9]+" inputMode="numeric" className={styles.input}/><span className={styles.hint}>Satoshis for BTC, piconero for XMR, wei for ETH. Use the exact integer from your wallet.</span></label><label className={styles.field}>How was receipt verified?<textarea name="note" required minLength={10} maxLength={1000} className={styles.textarea}/></label><button disabled={busy} className={styles.button}>Record verified receipt</button>{error&&<Notice error>{error}</Notice>}</form></details>;
}
function WalletSetup({onSaved}:{onSaved:()=>void}){
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);const values=Object.fromEntries(new FormData(e.currentTarget));const result=await backend().rpc("isitusa_wallet",{asset:values.asset,address:values.address,note:values.note});setBusy(false);if(result.error)setError(result.error.message);else onSaved();}
 return <details className={styles.section}><summary className="text-link">Set a verified receiving address</summary><form className={styles.form} onSubmit={save}><Notice>Public receiving addresses only. Verify ownership, checksum, and the full address in your own wallet before publishing. Never paste a seed phrase, private key, or Monero view key.</Notice><label className={styles.field}>Asset and network<select name="asset" className={styles.select}><option value="BTC">Bitcoin mainnet</option><option value="XMR">Monero mainnet</option><option value="ETH">Ethereum mainnet</option></select></label><label className={styles.field}>Receiving address<input name="address" required maxLength={120} className={styles.input} autoComplete="off"/></label><label className={styles.field}>Verification record<textarea name="note" minLength={10} maxLength={1000} required className={styles.textarea} placeholder="When and how you checked ownership, checksum, and network."/></label><label className={styles.choice}><input type="checkbox" required/><span>I verified this address in an IsItUSA-controlled wallet. Publishing replaces the active address for this asset.</span></label><button className={styles.button} disabled={busy}>Publish receiving address</button>{error&&<Notice error>{error}</Notice>}</form></details>;
}
