"use client";
import { useState } from "react";
import type { Permission } from "@/lib/participation/contracts";
import { WorkspaceFrame, WorkspaceLoading, WorkspaceOverview, type WorkspaceTab } from "./workspace-frame";
import { styles } from "@/components/participation/shared";
import admin from "./admin.module.css";

export function WorkspacePreview() {
  const [tab,setTab]=useState<WorkspaceTab>("overview"),[role,setRole]=useState("owner"),[state,setState]=useState("populated"),[selected,setSelected]=useState(false),[search,setSearch]=useState(""),[filter,setFilter]=useState("all");
  const can=(permission:Permission)=>role==="owner"||permission==="review";
  const examples=[{label:"Spotted lanternfly",place:"Hamilton County, Ohio",status:"Submitted"},{label:"Unidentified climbing vine",place:"Fulton County, Georgia",status:"In review"},{label:"Japanese stiltgrass",place:"Fairfax County, Virginia",status:"More information needed"}];
  const rows=state==="empty"?[]:examples.filter(row=>row.label.toLowerCase().includes(search.toLowerCase())&&(filter==="all"||filter===row.status));
  const navigate=(next:WorkspaceTab)=>{setTab(next);setSelected(false);setSearch("");setFilter("all");};
  return <><div className={admin.previewNote}>Design verification only. All records below are fictional. This preview cannot read or change project records.<div className={styles.row}><label>Preview role <select value={role} onChange={e=>{setRole(e.target.value);navigate("overview");}}><option value="owner">Owner</option><option value="reviewer">Volunteer reviewer</option></select></label><label>Preview state <select value={state} onChange={e=>setState(e.target.value)}><option value="populated">Populated</option><option value="empty">Empty</option><option value="loading">Loading</option><option value="error">Error</option></select></label></div></div>
  <WorkspaceFrame name="Design review" owner={role==="owner"} tab={tab} can={can} loading={state==="loading"} refreshedAt={null} onTab={navigate} onRefresh={()=>setState("populated")} onSignOut={()=>{window.location.href="/admin";}}>
    {state==="loading"?<WorkspaceLoading/>:state==="error"?<div role="alert" className={styles.notice}>The workspace could not load. Your records have not changed. Use Refresh to try again.</div>:tab==="overview"?<WorkspaceOverview counts={state==="empty"?{pending:0,confirmed:0,finance:0}:{pending:7,confirmed:124,finance:16}} can={can} onTab={navigate}/>:tab==="review"?<><form className={admin.toolbar} onSubmit={e=>e.preventDefault()}><label>Search observations<input className={styles.input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Species or observer identification"/></label><label>Show<select className={styles.select} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All records</option><option>Submitted</option><option>In review</option><option>More information needed</option></select></label></form><div className={selected?admin.split:undefined}><div>{rows.length?<div className={admin.tableWrap}><table className={admin.table}><thead><tr><th>Observation</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><td><button onClick={()=>setSelected(true)}>{row.label}</button><div className={styles.hint}>{row.place}</div></td><td><span className={admin.pill}>{row.status}</span></td></tr>)}</tbody></table></div>:<div className={admin.empty}><strong>No observations match these filters.</strong><p>Clear the search or choose another status.</p></div>}</div>{selected&&<article className={admin.detail}><div className={admin.detailClose}><button onClick={()=>setSelected(false)}>Close observation</button></div><h3>Example observation</h3><dl><dt>Observed</dt><dd>October 7, 2026</dd><dt>County</dt><dd>Hamilton County, Ohio</dd><dt>Notes</dt><dd>Fictional record used to verify this reading panel and its mobile layout.</dd></dl><h4>Compare the identification</h4><p className={styles.hint}>The production workspace provides a catalog picker, private photographs and an audited review form here.</p></article>}</div></>:<div className={admin.empty}><strong>{tab==="audience"?"Email audience":tab==="finance"?"Contribution records":tab==="team"?"Team access":tab==="analytics"?"Site activity":"Service connections"}</strong><p>This presentation preview does not connect to live services. Authenticated workflow verification is a separate check.</p></div>}
  </WorkspaceFrame></>;
}
