import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { countySpeciesStatusOverrides } from "@/data/source/county-species-status-overrides";
import type { CountySpeciesNonPresenceStatus } from "@/lib/data/types";

type SpeciesRecord = {
  id: string;
  commonName: string;
  scientificName: string;
  category: string;
  profileType: string;
};

type CountyRecord = {
  countyFips: string;
  name: string;
  stateCode: string;
  stateName: string;
};

type CountyPresenceRecord = {
  countyFips: string;
  speciesIds: string[];
};

type CountyCoverageSnapshot = {
  source: string;
  snapshotDate: string;
};

type CountyMatrixEntry = {
  countyFips: string;
  name: string;
  presentVerifiedSpeciesIds: string[];
  verifiedAbsentSpeciesIds: string[];
  notDetectedSpeciesIds: string[];
  knownDeterminations: number;
  unknownDeterminations: number;
  knownPercent: number;
  targetGap: number;
};

type SpeciesMatrixEntry = {
  speciesId: string;
  commonName: string;
  scientificName: string;
  category: string;
  profileType: string;
  presentVerifiedCountyFips: string[];
  verifiedAbsentCountyFips: string[];
  notDetectedCountyFips: string[];
  knownCountyCount: number;
  unknownCountyCount: number;
};

const TARGET_KNOWN_PERCENT = 90;

function readJson<T>(filepath: string): T {
  return JSON.parse(readFileSync(filepath, "utf8")) as T;
}

function roundPercent(value: number) {
  return Number(value.toFixed(2));
}

function sortUnique(values: string[]) {
  return [...new Set(values)].sort();
}

function ensureKnownState(stateCode: string, counties: CountyRecord[]) {
  if (counties.length === 0) {
    throw new Error(`Unknown state code or no generated counties for ${stateCode}.`);
  }
}

function validateStatusOverrides(speciesIds: Set<string>, countiesByFips: Map<string, CountyRecord>, stateCode: string) {
  for (const override of countySpeciesStatusOverrides) {
    if (!speciesIds.has(override.speciesId)) {
      throw new Error(`County-species status override references unknown species: ${override.speciesId}`);
    }

    const county = countiesByFips.get(override.countyFips);
    if (!county) {
      throw new Error(`County-species status override references unknown county: ${override.countyFips}`);
    }

    if (county.stateCode !== stateCode) {
      continue;
    }

    if (override.status !== "verified-absent" && override.status !== "not-detected") {
      throw new Error(`Unsupported county-species status for ${override.countyFips}:${override.speciesId}`);
    }
  }
}

function addStatus(
  index: Map<string, Map<CountySpeciesNonPresenceStatus, Set<string>>>,
  countyFips: string,
  status: CountySpeciesNonPresenceStatus,
  speciesId: string,
) {
  if (!index.has(countyFips)) {
    index.set(countyFips, new Map());
  }

  const countyStatuses = index.get(countyFips)!;
  if (!countyStatuses.has(status)) {
    countyStatuses.set(status, new Set());
  }

  countyStatuses.get(status)!.add(speciesId);
}

function writeStateMarkdown(filepath: string, matrix: {
  stateCode: string;
  stateName: string;
  summary: {
    countyCount: number;
    speciesCount: number;
    totalDeterminations: number;
    targetKnownDeterminationsPerCounty: number;
    targetKnownDeterminationsTotal: number;
    presentVerifiedDeterminations: number;
    verifiedAbsentDeterminations: number;
    notDetectedDeterminations: number;
    knownDeterminations: number;
    unknownDeterminations: number;
    knownPercent: number;
    countiesAtTarget: number;
  };
  counties: CountyMatrixEntry[];
}) {
  const lowestCoverage = [...matrix.counties]
    .sort((left, right) => left.knownDeterminations - right.knownDeterminations || left.name.localeCompare(right.name))
    .slice(0, 10);

  const highestCoverage = [...matrix.counties]
    .sort((left, right) => right.knownDeterminations - left.knownDeterminations || left.name.localeCompare(right.name))
    .slice(0, 10);

  const lines = [
    `# ${matrix.stateName} County-Species Coverage Matrix`,
    "",
    `State code: \`${matrix.stateCode}\``,
    `Generated by: \`npm run build:county-matrix -- ${matrix.stateCode}\``,
    "",
    "## Summary",
    "",
    `- Counties: \`${matrix.summary.countyCount}\``,
    `- Species in catalog: \`${matrix.summary.speciesCount}\``,
    `- County-species determinations: \`${matrix.summary.totalDeterminations}\``,
    `- Target known determinations per county for 90 percent: \`${matrix.summary.targetKnownDeterminationsPerCounty}\``,
    `- Target known determinations statewide for 90 percent in every county: \`${matrix.summary.targetKnownDeterminationsTotal}\``,
    `- Verified present determinations: \`${matrix.summary.presentVerifiedDeterminations}\``,
    `- Verified absent determinations: \`${matrix.summary.verifiedAbsentDeterminations}\``,
    `- Not-detected determinations: \`${matrix.summary.notDetectedDeterminations}\``,
    `- Known determinations: \`${matrix.summary.knownDeterminations}\``,
    `- Unknown determinations: \`${matrix.summary.unknownDeterminations}\``,
    `- Known percent: \`${matrix.summary.knownPercent}%\``,
    `- Counties at 90 percent target: \`${matrix.summary.countiesAtTarget}/${matrix.summary.countyCount}\``,
    "",
    "## Status Rules",
    "",
    "- `verified-present`: generated from imported county presence sources or manual authoritative presence overrides.",
    "- `verified-absent`: only for a county and species when a reputable source explicitly supports absence.",
    "- `not-detected`: only for a county and species when a reputable survey or monitoring source looked and did not detect it.",
    "- `unknown`: the default for every county-species pair that has no verified status yet.",
    "",
    "Unknown does not mean absent. It means no defensible county-species determination has been added yet.",
    "",
    "## Lowest Coverage Counties",
    "",
    "| County FIPS | County | Known | Unknown | Known percent | Gap to 90 percent |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
    ...lowestCoverage.map(
      (county) =>
        `| ${county.countyFips} | ${county.name} | ${county.knownDeterminations} | ${county.unknownDeterminations} | ${county.knownPercent}% | ${county.targetGap} |`,
    ),
    "",
    "## Highest Coverage Counties",
    "",
    "| County FIPS | County | Known | Unknown | Known percent | Gap to 90 percent |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
    ...highestCoverage.map(
      (county) =>
        `| ${county.countyFips} | ${county.name} | ${county.knownDeterminations} | ${county.unknownDeterminations} | ${county.knownPercent}% | ${county.targetGap} |`,
    ),
    "",
    "## Maintenance",
    "",
    "Regenerate this state after county presence imports, manual authoritative presence overrides, or non-presence status overrides change.",
    "",
    "Do not hand-edit the generated JSON matrix. Add new non-presence determinations to `src/data/source/county-species-status-overrides.ts`, rerun the generator, and validate the diff.",
    "",
  ];

  writeFileSync(filepath, `${lines.join("\n")}\n`);
}

const requestedStateCode = process.argv[2]?.toUpperCase();

if (!requestedStateCode) {
  console.error("Usage: npm run build:county-matrix -- <STATE>");
  process.exit(1);
}

const species = readJson<SpeciesRecord[]>(path.join(process.cwd(), "src/data/generated/species.json"));
const countiesIndex = readJson<Record<string, CountyRecord>>(path.join(process.cwd(), "src/data/generated/counties.json"));
const presenceIndex = readJson<Record<string, CountyPresenceRecord>>(path.join(process.cwd(), "src/data/generated/presence.json"));
const countySnapshot = readJson<CountyCoverageSnapshot>(
  path.join(process.cwd(), "src/data/source/county-presence-snapshot.json"),
);

const speciesIds = new Set(species.map((entry) => entry.id));
const counties = Object.values(countiesIndex)
  .filter((county) => county.stateCode === requestedStateCode)
  .sort((left, right) => left.countyFips.localeCompare(right.countyFips));
const countiesByFips = new Map(Object.values(countiesIndex).map((county) => [county.countyFips, county]));

ensureKnownState(requestedStateCode, counties);
validateStatusOverrides(speciesIds, countiesByFips, requestedStateCode);

const stateName = counties[0]!.stateName;
const targetKnownDeterminationsPerCounty = Math.ceil(species.length * (TARGET_KNOWN_PERCENT / 100));
const nonPresenceByCounty = new Map<string, Map<CountySpeciesNonPresenceStatus, Set<string>>>();

for (const override of countySpeciesStatusOverrides) {
  const county = countiesByFips.get(override.countyFips);
  if (county?.stateCode !== requestedStateCode) {
    continue;
  }

  addStatus(nonPresenceByCounty, override.countyFips, override.status, override.speciesId);
}

const speciesCountyPresence = new Map<string, Set<string>>();
const speciesVerifiedAbsent = new Map<string, Set<string>>();
const speciesNotDetected = new Map<string, Set<string>>();

const countyEntries: CountyMatrixEntry[] = counties.map((county) => {
  const presentVerifiedSpeciesIds = sortUnique(presenceIndex[county.countyFips]?.speciesIds ?? []);
  const presentSpeciesSet = new Set(presentVerifiedSpeciesIds);
  const countyNonPresence = nonPresenceByCounty.get(county.countyFips);
  const verifiedAbsentSpeciesIds = sortUnique([...(countyNonPresence?.get("verified-absent") ?? [])]);
  const notDetectedSpeciesIds = sortUnique([...(countyNonPresence?.get("not-detected") ?? [])]);

  for (const speciesId of verifiedAbsentSpeciesIds) {
    if (presentSpeciesSet.has(speciesId)) {
      throw new Error(
        `${county.countyFips}:${speciesId} is both verified-present and verified-absent. Resolve the source conflict first.`,
      );
    }
  }

  for (const speciesId of notDetectedSpeciesIds) {
    if (presentSpeciesSet.has(speciesId)) {
      throw new Error(
        `${county.countyFips}:${speciesId} is both verified-present and not-detected. Resolve the source conflict first.`,
      );
    }
  }

  for (const speciesId of presentVerifiedSpeciesIds) {
    if (!speciesCountyPresence.has(speciesId)) {
      speciesCountyPresence.set(speciesId, new Set());
    }
    speciesCountyPresence.get(speciesId)!.add(county.countyFips);
  }

  for (const speciesId of verifiedAbsentSpeciesIds) {
    if (!speciesVerifiedAbsent.has(speciesId)) {
      speciesVerifiedAbsent.set(speciesId, new Set());
    }
    speciesVerifiedAbsent.get(speciesId)!.add(county.countyFips);
  }

  for (const speciesId of notDetectedSpeciesIds) {
    if (!speciesNotDetected.has(speciesId)) {
      speciesNotDetected.set(speciesId, new Set());
    }
    speciesNotDetected.get(speciesId)!.add(county.countyFips);
  }

  const knownDeterminations =
    presentVerifiedSpeciesIds.length + verifiedAbsentSpeciesIds.length + notDetectedSpeciesIds.length;
  const unknownDeterminations = species.length - knownDeterminations;

  return {
    countyFips: county.countyFips,
    name: county.name,
    presentVerifiedSpeciesIds,
    verifiedAbsentSpeciesIds,
    notDetectedSpeciesIds,
    knownDeterminations,
    unknownDeterminations,
    knownPercent: roundPercent((knownDeterminations / species.length) * 100),
    targetGap: Math.max(0, targetKnownDeterminationsPerCounty - knownDeterminations),
  };
});

const speciesEntries: SpeciesMatrixEntry[] = species
  .map((entry) => {
    const presentVerifiedCountyFips = sortUnique([...(speciesCountyPresence.get(entry.id) ?? [])]);
    const verifiedAbsentCountyFips = sortUnique([...(speciesVerifiedAbsent.get(entry.id) ?? [])]);
    const notDetectedCountyFips = sortUnique([...(speciesNotDetected.get(entry.id) ?? [])]);
    const knownCountyCount =
      presentVerifiedCountyFips.length + verifiedAbsentCountyFips.length + notDetectedCountyFips.length;

    return {
      speciesId: entry.id,
      commonName: entry.commonName,
      scientificName: entry.scientificName,
      category: entry.category,
      profileType: entry.profileType,
      presentVerifiedCountyFips,
      verifiedAbsentCountyFips,
      notDetectedCountyFips,
      knownCountyCount,
      unknownCountyCount: counties.length - knownCountyCount,
    };
  })
  .sort((left, right) => left.speciesId.localeCompare(right.speciesId));

const presentVerifiedDeterminations = countyEntries.reduce(
  (sum, county) => sum + county.presentVerifiedSpeciesIds.length,
  0,
);
const verifiedAbsentDeterminations = countyEntries.reduce(
  (sum, county) => sum + county.verifiedAbsentSpeciesIds.length,
  0,
);
const notDetectedDeterminations = countyEntries.reduce((sum, county) => sum + county.notDetectedSpeciesIds.length, 0);
const knownDeterminations =
  presentVerifiedDeterminations + verifiedAbsentDeterminations + notDetectedDeterminations;
const totalDeterminations = counties.length * species.length;

const matrix = {
  schemaVersion: 1,
  stateCode: requestedStateCode,
  stateName,
  statusDefinitions: {
    "verified-present":
      "A reputable source supports county-level presence through imported county presence data or a manual authoritative presence override.",
    "verified-absent": "A reputable source explicitly supports absence for the county and species.",
    "not-detected": "A reputable survey or monitoring source searched for the species and did not detect it.",
    unknown: "No defensible county-species determination has been added yet. Unknown does not mean absent.",
  },
  generatedFrom: {
    species: "src/data/generated/species.json",
    counties: "src/data/generated/counties.json",
    presence: "src/data/generated/presence.json",
    nonPresenceOverrides: "src/data/source/county-species-status-overrides.ts",
    countyPresenceSnapshotDate: countySnapshot.snapshotDate,
  },
  target: {
    knownPercent: TARGET_KNOWN_PERCENT,
    knownDeterminationsPerCounty: targetKnownDeterminationsPerCounty,
    knownDeterminationsTotal: targetKnownDeterminationsPerCounty * counties.length,
  },
  summary: {
    countyCount: counties.length,
    speciesCount: species.length,
    totalDeterminations,
    targetKnownDeterminationsPerCounty,
    targetKnownDeterminationsTotal: targetKnownDeterminationsPerCounty * counties.length,
    presentVerifiedDeterminations,
    verifiedAbsentDeterminations,
    notDetectedDeterminations,
    knownDeterminations,
    unknownDeterminations: totalDeterminations - knownDeterminations,
    knownPercent: roundPercent((knownDeterminations / totalDeterminations) * 100),
    countiesAtTarget: countyEntries.filter(
      (county) => county.knownDeterminations >= targetKnownDeterminationsPerCounty,
    ).length,
  },
  counties: countyEntries,
  species: speciesEntries,
};

const outputDir = path.join(process.cwd(), "docs/county-coverage/states");
mkdirSync(outputDir, { recursive: true });

writeFileSync(
  path.join(outputDir, `${requestedStateCode}.json`),
  `${JSON.stringify(matrix, null, 2)}\n`,
);
writeStateMarkdown(path.join(outputDir, `${requestedStateCode}.md`), matrix);

console.log(
  JSON.stringify(
    {
      stateCode: matrix.stateCode,
      stateName: matrix.stateName,
      summary: matrix.summary,
      output: [`docs/county-coverage/states/${requestedStateCode}.json`, `docs/county-coverage/states/${requestedStateCode}.md`],
    },
    null,
    2,
  ),
);
