import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { stateSpeciesDenominators } from "@/data/source/state-species-denominators";

type SpeciesRecord = {
  id: string;
  commonName: string;
  scientificName: string;
  category: string;
  profileType: string;
};

type CountyMatrix = {
  stateCode: string;
  stateName: string;
  counties: Array<{
    countyFips: string;
    presentVerifiedSpeciesIds: string[];
  }>;
};

type DenominatorSnapshot = {
  sourceUrl: string;
  species: Array<{
    subjectId?: number;
    commonName: string;
    scientificName: string;
    family?: string;
    nativity?: string;
  }>;
};

type ReconciledEntry = {
  commonName: string;
  scientificName: string;
  sourceCategory: string;
  sourceStatus?: string;
  matchStatus: "catalog-matched" | "catalog-unmatched" | "ambiguous-source";
  matchedSpeciesId?: string;
  matchedCommonName?: string;
  matchedScientificName?: string;
  matchedCategory?: string;
  matchedProfileType?: string;
  eddMapsSubjectId?: number;
  sourceFamily?: string;
  sourceNativity?: string;
  presentVerifiedCountyCount: number;
  presentVerifiedCountyFips: string[];
  notes?: string;
};

function readJson<T>(filepath: string): T {
  return JSON.parse(readFileSync(filepath, "utf8")) as T;
}

function normalizeScientificName(value: string) {
  return value
    .toLowerCase()
    .replace(/\b(spp|ssp|subsp|var)\.?\b/g, "")
    .replace(/x/g, "x")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}

function sortUnique(values: string[]) {
  return [...new Set(values)].sort();
}

function readDenominatorSnapshot(listId: string) {
  const snapshotPath = path.join(
    process.cwd(),
    `src/data/source/state-denominator-snapshots/${listId.toLowerCase()}.json`,
  );

  if (!existsSync(snapshotPath)) {
    return null;
  }

  return readJson<DenominatorSnapshot>(snapshotPath);
}

function writeMarkdown(filepath: string, report: {
  stateCode: string;
  stateName: string;
  listId: string;
  listLabel: string;
  sourceUrl: string;
  summary: {
    listSpeciesCount: number;
    catalogMatchedCount: number;
    catalogUnmatchedCount: number;
    liveMappedInStateCount: number;
    catalogMatchedButUnmappedCount: number;
  };
  entries: ReconciledEntry[];
}) {
  const catalogMatchedButUnmapped = report.entries.filter(
    (entry) => entry.matchStatus === "catalog-matched" && entry.presentVerifiedCountyCount === 0,
  );
  const catalogUnmatched = report.entries.filter((entry) => entry.matchStatus !== "catalog-matched");
  const liveMapped = report.entries
    .filter((entry) => entry.presentVerifiedCountyCount > 0)
    .sort((left, right) => right.presentVerifiedCountyCount - left.presentVerifiedCountyCount);

  const lines = [
    `# ${report.stateName} ${report.listId} Reconciliation`,
    "",
    `State code: \`${report.stateCode}\``,
    `Source: [${report.listLabel}](${report.sourceUrl})`,
    `Generated by: \`node --import tsx scripts/reconcile-state-denominators.ts ${report.stateCode} ${report.listId}\``,
    "",
    "## Summary",
    "",
    `- List species: \`${report.summary.listSpeciesCount}\``,
    `- Catalog matched: \`${report.summary.catalogMatchedCount}\``,
    `- Catalog unmatched or ambiguous: \`${report.summary.catalogUnmatchedCount}\``,
    `- Live mapped in state: \`${report.summary.liveMappedInStateCount}\``,
    `- Catalog matched but not live mapped in state: \`${report.summary.catalogMatchedButUnmappedCount}\``,
    "",
    "List membership is not county evidence. Use this report to select the next source-family import targets.",
    "",
    "## Catalog Matched But Not Live Mapped",
    "",
    "| Source common name | Source scientific name | Matched species ID | EDDMapS subject | Category | Notes |",
    "| --- | --- | --- | ---: | --- | --- |",
    ...catalogMatchedButUnmapped.map(
      (entry) =>
        `| ${entry.commonName} | ${entry.scientificName} | ${entry.matchedSpeciesId} | ${entry.eddMapsSubjectId ?? ""} | ${entry.sourceCategory} | ${entry.notes ?? ""} |`,
    ),
    "",
    "## Unmatched Or Ambiguous",
    "",
    "| Source common name | Source scientific name | EDDMapS subject | Source category | Notes |",
    "| --- | --- | ---: | --- | --- |",
    ...catalogUnmatched.map(
      (entry) =>
        `| ${entry.commonName} | ${entry.scientificName} | ${entry.eddMapsSubjectId ?? ""} | ${entry.sourceCategory} | ${entry.notes ?? ""} |`,
    ),
    "",
    "## Highest Current County Coverage",
    "",
    "| Source common name | Matched species ID | Verified-present counties |",
    "| --- | --- | ---: |",
    ...liveMapped
      .slice(0, 25)
      .map((entry) => `| ${entry.commonName} | ${entry.matchedSpeciesId} | ${entry.presentVerifiedCountyCount} |`),
    "",
  ];

  writeFileSync(filepath, `${lines.join("\n")}\n`);
}

const requestedStateCode = process.argv[2]?.toUpperCase();
const requestedListId = process.argv[3] ?? "ALIPC-2012";

if (!requestedStateCode) {
  console.error("Usage: node --import tsx scripts/reconcile-state-denominators.ts <STATE> [LIST_ID]");
  process.exit(1);
}

const denominatorEntries = stateSpeciesDenominators.filter(
  (entry) => entry.stateCode === requestedStateCode && entry.listId === requestedListId,
);

if (denominatorEntries.length === 0) {
  throw new Error(`No denominator entries found for ${requestedStateCode} ${requestedListId}.`);
}

const species = readJson<SpeciesRecord[]>(path.join(process.cwd(), "src/data/generated/species.json"));
const matrix = readJson<CountyMatrix>(path.join(process.cwd(), `docs/county-coverage/states/${requestedStateCode}.json`));
const denominatorSnapshot = readDenominatorSnapshot(requestedListId);
const speciesByNormalizedScientificName = new Map<string, SpeciesRecord>();
const snapshotByNormalizedScientificName = new Map<
  string,
  DenominatorSnapshot["species"][number]
>();

for (const entry of species) {
  speciesByNormalizedScientificName.set(normalizeScientificName(entry.scientificName), entry);
}

for (const entry of denominatorSnapshot?.species ?? []) {
  snapshotByNormalizedScientificName.set(normalizeScientificName(entry.scientificName), entry);
}

const presentCountyFipsBySpeciesId = new Map<string, string[]>();

for (const county of matrix.counties) {
  for (const speciesId of county.presentVerifiedSpeciesIds) {
    const countyFips = presentCountyFipsBySpeciesId.get(speciesId) ?? [];
    countyFips.push(county.countyFips);
    presentCountyFipsBySpeciesId.set(speciesId, countyFips);
  }
}

const entries = denominatorEntries.map((entry): ReconciledEntry => {
  const candidateNames = [entry.scientificName, ...(entry.reviewedAliases ?? [])];
  const sourceSnapshot = candidateNames
    .map((name) => snapshotByNormalizedScientificName.get(normalizeScientificName(name)))
    .find((candidate): candidate is DenominatorSnapshot["species"][number] => Boolean(candidate));

  if (entry.scientificName.toLowerCase().includes("spp")) {
    return {
      commonName: entry.commonName,
      scientificName: entry.scientificName,
      sourceCategory: entry.sourceCategory,
      sourceStatus: entry.sourceStatus,
      matchStatus: "ambiguous-source",
      eddMapsSubjectId: sourceSnapshot?.subjectId,
      sourceFamily: sourceSnapshot?.family,
      sourceNativity: sourceSnapshot?.nativity,
      presentVerifiedCountyCount: 0,
      presentVerifiedCountyFips: [],
      notes: entry.notes ?? "Source entry is not species-specific.",
    };
  }

  const matchedSpecies = candidateNames
    .map((name) => speciesByNormalizedScientificName.get(normalizeScientificName(name)))
    .find((candidate): candidate is SpeciesRecord => Boolean(candidate));

  if (!matchedSpecies) {
    return {
      commonName: entry.commonName,
      scientificName: entry.scientificName,
      sourceCategory: entry.sourceCategory,
      sourceStatus: entry.sourceStatus,
      matchStatus: "catalog-unmatched",
      eddMapsSubjectId: sourceSnapshot?.subjectId,
      sourceFamily: sourceSnapshot?.family,
      sourceNativity: sourceSnapshot?.nativity,
      presentVerifiedCountyCount: 0,
      presentVerifiedCountyFips: [],
      notes: entry.notes,
    };
  }

  const presentVerifiedCountyFips = sortUnique(presentCountyFipsBySpeciesId.get(matchedSpecies.id) ?? []);

  return {
    commonName: entry.commonName,
    scientificName: entry.scientificName,
    sourceCategory: entry.sourceCategory,
    sourceStatus: entry.sourceStatus,
    matchStatus: "catalog-matched",
    matchedSpeciesId: matchedSpecies.id,
    matchedCommonName: matchedSpecies.commonName,
    matchedScientificName: matchedSpecies.scientificName,
    matchedCategory: matchedSpecies.category,
    matchedProfileType: matchedSpecies.profileType,
    eddMapsSubjectId: sourceSnapshot?.subjectId,
    sourceFamily: sourceSnapshot?.family,
    sourceNativity: sourceSnapshot?.nativity,
    presentVerifiedCountyCount: presentVerifiedCountyFips.length,
    presentVerifiedCountyFips,
    notes: entry.notes,
  };
});

const catalogMatchedCount = entries.filter((entry) => entry.matchStatus === "catalog-matched").length;
const liveMappedInStateCount = entries.filter((entry) => entry.presentVerifiedCountyCount > 0).length;

const report = {
  stateCode: requestedStateCode,
  stateName: matrix.stateName,
  listId: requestedListId,
  listLabel: denominatorEntries[0]!.listLabel,
  sourceUrl: denominatorEntries[0]!.source.url,
  denominatorSnapshotUrl: denominatorSnapshot?.sourceUrl,
  summary: {
    listSpeciesCount: entries.length,
    catalogMatchedCount,
    catalogUnmatchedCount: entries.length - catalogMatchedCount,
    liveMappedInStateCount,
    catalogMatchedButUnmappedCount: entries.filter(
      (entry) => entry.matchStatus === "catalog-matched" && entry.presentVerifiedCountyCount === 0,
    ).length,
  },
  entries,
};

const outputDir = path.join(process.cwd(), "docs/county-coverage/states");
mkdirSync(outputDir, { recursive: true });
writeFileSync(
  path.join(outputDir, `${requestedStateCode}-${requestedListId.toLowerCase()}-reconciliation.json`),
  `${JSON.stringify(report, null, 2)}\n`,
);
writeMarkdown(path.join(outputDir, `${requestedStateCode}-${requestedListId.toLowerCase()}-reconciliation.md`), report);

console.log(JSON.stringify(report.summary, null, 2));
