import assert from 'node:assert/strict';
import { epaNrsaPositiveValue as qualify, parseEpaNrsaCsv, epaNrsaParametersSchema, EPA_NRSA_SOURCE, EPA_NRSA_ADAPTER, EPA_NRSA_VERSION } from '@/lib/research/epa-nrsa-fish-counts';
import { isCommittedSnapshotReplayReceipt } from '@/lib/research/validate-run';
const crlf = Buffer.from('name,note\r\ncarp,"first\r\nsecond"\r\ntrout,last\r\n');
const parsed = parseEpaNrsaCsv(crlf);
assert.equal(parsed.length, 2); assert.equal(parsed[0].physicalEndLineOneBased, 3); assert.equal(parsed[1].physicalEndLineOneBased, 4);
assert.deepEqual(parsed[0].raw, Buffer.from('carp,"first\r\nsecond"\r\n')); assert.deepEqual(parsed[1].raw, Buffer.from('trout,last\r\n'));
const lf = parseEpaNrsaCsv(Buffer.from('name,note\ncarp,ok\ntrout,end'));
assert.equal(lf[0].raw.toString(), 'carp,ok\n'); assert.equal(lf[1].physicalEndLineOneBased, 3);
assert.throws(() => parseEpaNrsaCsv(Buffer.from('name,name\r\na,b\r\n')));
assert.throws(() => parseEpaNrsaCsv(Buffer.from('name,note\r\na\r\n')));
assert.throws(() => parseEpaNrsaCsv(Buffer.from([0xff, 0xfe, 0x00])));
const county = {countyFips: '01067', stateCode: 'AL', status: 'active', shortName: 'Henry', legalName: 'Henry County', aliases: ['Henry', 'Henry County']};
const fish = {UID: '2023949', SITE_ID: 'NRS24_AL_10001', UNIQUE_ID: 'NRS_AL-10101', DATE_COL: '8/12/2024', VISIT_NO: '1', PSTL_CODE: 'AL', TAXA_ID: '78', FINAL_NAME: 'COMMON CARP', TOTAL: '3', ANOM_CT: '', COUNT_6: '1', COUNT_12: '2', COUNT_18: '', COUNT_19: '', IS_DISTINCT: '1', FISH_SAMPLING: '', SAMPLED_FISH: 'YES-SUFFICIENT'};
const site = {UID: fish.UID, SITE_ID: fish.SITE_ID, UNIQUE_ID: fish.UNIQUE_ID, DATE_COL: fish.DATE_COL, VISIT_NO: fish.VISIT_NO, PSTL_CODE: 'AL', STATECTY: 'F01067', CNTYNAME: 'Henry', EVAL_CAT: 'Target_Sampled', DSGN_CYCLE: '2023-24', STUDY: 'NRSA', YEAR: '2024'};
const taxon = {TAXA_ID: '78', FINAL_NAME: 'COMMON CARP', GENUS: 'CYPRINUS', SPECIES: 'CARPIO'};
const name = 'Cyprinus carpio';
assert.equal(qualify(fish, site, taxon, county, name).date, '2024-08-12');
let rejected = 0;
function invalid(r = fish, s = site, t = taxon, c: typeof county | undefined = county) {assert.equal(qualify(r, s, t, c, name).date, null); rejected++;}
for (const flag of ['NO_FISH', 'NO_PERMIT', 'EQUIPMENT_FAILURE', 'NO_FISH_OTHER']) invalid({...fish, FISH_SAMPLING: flag});
for (const total of ['0', '-1', '1.5', 'NaN', '9007199254740992']) invalid({...fish, TOTAL: total});
invalid({...fish, IS_DISTINCT: '0'}); invalid({...fish, UID: 'other'}); invalid({...fish, SITE_ID: 'other'});
invalid({...fish, TAXA_ID: 'other'}); invalid({...fish, FINAL_NAME: 'OTHER'});
invalid(fish, {...site, STATECTY: 'F99999'}); invalid(fish, {...site, CNTYNAME: 'Other'});
invalid(fish, {...site, PSTL_CODE: 'ZZ'}); invalid(fish, {...site, EVAL_CAT: 'Non_Target'});
invalid({...fish, ANOM_CT: '4'}); invalid({...fish, ANOM_CT: '-1'}); invalid(fish, {...site, STUDY: 'OTHER'}); invalid(fish, {...site, DSGN_CYCLE: '2021-22'});
invalid({...fish, COUNT_6: '99'}); invalid({...fish, COUNT_6: '1.0'}); invalid(fish, site, {...taxon, GENUS: 'OTHER'});
invalid(fish, site, taxon, {...county, status: 'retired'});
assert.equal(qualify(fish, site, taxon, undefined, name).date, null); rejected++;
for (const date of ['2/30/2024', '13/1/2024', '8/12/2022', '8/12/2026']) invalid({...fish, DATE_COL: date}, {...site, DATE_COL: date});
invalid(fish, {...site, YEAR: '2023'});
for (const effort of ['NO-SITE CONDITIONS', 'YES>20CW<500', 'YES-SEINING ONLY']) assert.equal(qualify({...fish, SAMPLED_FISH: effort}, site, taxon, county, name).date, '2024-08-12');
assert.equal(qualify(fish, {...site, CNTYNAME: 'Henry County'}, taxon, county, name).date, '2024-08-12');
const parameters = {mode: 'retained-reviewed-fish-counts', stateCode: 'AL', methodReviewPath: 'src/data/research/source-method-reviews/epa-nrsa-fish-counts-fixture.json', methodReviewSha256: 'a'.repeat(64), candidatePairs: ['01067:cyprinus-carpio'], candidateLimit: 1};
assert(epaNrsaParametersSchema.safeParse(parameters).success);
const receipt = {source_id: EPA_NRSA_SOURCE, adapter_id: EPA_NRSA_ADAPTER, adapter_version: EPA_NRSA_VERSION, parameters};
assert(isCommittedSnapshotReplayReceipt(receipt));
for (const overrides of [{source_id: 'other'}, {adapter_id: 'other'}, {adapter_version: '2.0.0'}, {parameters: {...parameters, mode: 'fresh-http'}}, {parameters: {...parameters, methodReviewPath: '../outside.json'}}, {parameters: {...parameters, methodReviewSha256: 'invalid'}}]) {assert(!isCommittedSnapshotReplayReceipt({...receipt, ...overrides})); rejected++;}
assert(!epaNrsaParametersSchema.safeParse({...parameters, methodReviewPath: '../outside.json'}).success);
assert(!epaNrsaParametersSchema.safeParse({...parameters, extra: true}).success);
console.log(JSON.stringify({passed: true, rejectedCases: rejected, preservedEffortQualifications: 3, providerRequests: 0, fixtureOnly: true}));
