import assert from "node:assert/strict";
import { parseSpecimenDate, specimenRecordIdentity, specimenRowSha256, SpecimenIdentityAudit } from "./research/specimen-record-metadata";

const asOf = "2026-09-06";
assert.deepEqual(parseSpecimenDate({}, asOf), { status: "undated", eventDate: null, year: null });
assert.deepEqual(parseSpecimenDate({ eventDate: "  ", year: "" }, asOf), { status: "undated", eventDate: null, year: null });
assert.equal(parseSpecimenDate({ eventDate: "unknown" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ year: "unknown" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ eventDate: "2024-02-30" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ eventDate: "2023-02-29" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ eventDate: "2024-13" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ eventDate: "2024-06-01", year: "2025" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ eventDate: "2026-09-07" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ year: "2027" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ eventDate: "2024-01-01", month: "2" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ year: "2026", month: "10", day: "1" }, asOf).status, "rejected");
assert.equal(parseSpecimenDate({ year: "2023", month: "2", day: "29" }, asOf).status, "rejected");
assert.deepEqual(parseSpecimenDate({ year: "1901", month: "6", day: "5" }, asOf), { status: "dated", eventDate: "1901-06-05", year: 1901 });
assert.equal(parseSpecimenDate({ month: "06" }, asOf).status, "rejected");
for (const interval of ["1901/1902", "1912-07-29/1912-07-11", "1922-09-18/1922-10-01", "1981-07-16/1981-07-16"]) {
  assert.deepEqual(parseSpecimenDate({ eventDate: interval }, asOf), { status: "rejected", reason: "event-date-interval-requires-review" });
}
assert.equal(parseSpecimenDate({ verbatimEventDate: "June 1910" }, asOf).status, "rejected");
assert.deepEqual(parseSpecimenDate({ eventDate: "2024-02-29", year: "2024" }, asOf), { status: "dated", eventDate: "2024-02-29", year: 2024 });
assert.deepEqual(parseSpecimenDate({ year: "1901" }, asOf), { status: "dated", eventDate: "1901", year: 1901 });
assert.deepEqual(parseSpecimenDate({ eventDate: "2026-09" }, asOf), { status: "dated", eventDate: "2026-09", year: 2026 });
assert.throws(() => parseSpecimenDate({}, "2026-02-30"), /valid explicit/u);
assert.equal(specimenRecordIdentity({}), null);
assert.equal(specimenRecordIdentity({ id: "invalid\u0000id" }), null);
assert.deepEqual(specimenRecordIdentity({ id: "12" }), { recordId: "12", occurrenceId: "", identityKey: "core:12" });
assert.deepEqual(specimenRecordIdentity({ occurrenceID: "12" }), { recordId: "", occurrenceId: "12", identityKey: "occurrence:12" });
const row = { id: "12", occurrenceID: "urn:specimen:abc", county: "Adams", genus: "Agrostis" };
const audit = new SpecimenIdentityAudit(new Map([["core:12", specimenRowSha256(row)]]));
audit.observe(row);
audit.observe({ ...row, county: "Another county", basisOfRecord: "FossilSpecimen" });
assert.deepEqual(audit.result().conflictingIdentities, ["core:12"]);
assert.deepEqual(audit.result().missingIdentities, []);
const identical = new SpecimenIdentityAudit(new Map([["occurrence:urn:specimen:abc", specimenRowSha256(row)]]));
identical.observe(row);
identical.observe({ genus: "Agrostis", county: "Adams", occurrenceID: "urn:specimen:abc", id: "12" });
assert.deepEqual(identical.result().conflictingIdentities, []);
assert.deepEqual(new SpecimenIdentityAudit(new Map([["core:missing", "hash"]])).result().missingIdentities, ["core:missing"]);
console.log("Specimen metadata recovery: missing/invalid/future dates, stable identity fallback, and whole-archive collision audit passed.");
