import assert from 'node:assert/strict';
import fs from 'node:fs';
import { gunzipSync, gzipSync } from 'node:zlib';
import { qualifyEbirdOriginal as qualify, readEbirdArchive, ebirdOriginalDate, ebirdParametersSchema, EBIRD_MODE } from '@/lib/research/ebird-original-observations';
import { sha256 } from '@/lib/research/run-files';
const read = (p: string) => fs.readFileSync(p);
const evaluation = JSON.parse(read('ops/national-research/evaluations/ebird-eod-original-field-pilot-20260909-r19.json').toString());
const metadata = JSON.parse(read('ops/national-research/evaluations/ebird-eod-public-metadata-20260909-r19.json').toString());
const descriptor = ({path, bytes, sha256}: {path:string; bytes:number; sha256:string}) => ({path, bytes, sha256});
const source = readEbirdArchive(descriptor(evaluation.artifact), read), context = readEbirdArchive(descriptor(metadata.artifact), read);
const c = '.cache/research/campaigns/20260908-r19-ebird-bulk/';
const json = (p: string) => JSON.parse(source(p).toString());
const rows = JSON.parse(gunzipSync(source(c+'public-pilot-20260909/records.json.gz')).toString()).results;
const originals = new Map([...json(c+'public-pilot-verbatim-20260909/receipt.json').responses, ...json(c+'public-pilot-verbatim-remaining-20260909/receipt.json').responses].map((d: any) => [d.key, JSON.parse(gunzipSync(source(d.path)).toString())]));
const dataset = JSON.parse(gunzipSync(context(c+'taxonomy-discovery-20260909/dataset.json.gz')).toString());
const counties = JSON.parse(read('src/data/research/county-equivalent-registry.json').toString()).countyEquivalents;
const name='Brotogeris versicolurus', key=2479582, tags=dataset.machineTags, term=(n:string)=>'http://rs.tdwg.org/dwc/terms/'+n;
for(const r of rows) assert.equal(qualify(r, originals.get(r.key)!, counties, name, key, tags).reason,null,'Retained record '+r.key);
const r=rows.find((r:any)=>r.key===5297997915), o:any=originals.get(r.key)!;
assert.equal(o[term('locality')],'At home, Milpitas');
assert.equal(qualify(r,o,counties,name,key,tags).county?.countyFips,'06085');
assert.equal(qualify({...r,coordinateUncertaintyInMeters:undefined},o,counties,name,key,tags).reason,null);
let adverse=0;
function reject(rr=r,oo=o,cc=counties,tt=tags){assert.notEqual(qualify(rr,oo,cc,name,key,tt).reason,null);adverse++;}
for(const [field,value]of Object.entries({key:1,datasetKey:'other',countryCode:'CA',species:'Brotogeris chiriri',speciesKey:1,acceptedTaxonKey:1,taxonRank:'GENUS',taxonomicStatus:'SYNONYM',basisOfRecord:'PRESERVED_SPECIMEN',occurrenceStatus:'ABSENT',occurrenceID:'wrong',eventDate:'2024-02-30',year:2025,month:1,day:1,individualCount:0,license:'unapproved',issues:['COUNTRY_COORDINATE_MISMATCH'],stateProvince:'Florida',county:'Los Angeles',decimalLatitude:0,captive:true}))reject({...r,[field]:value});
for(const field of ['scientificName','class','country','institutionCode','collectionCode','basisOfRecord','occurrenceStatus','occurrenceID','stateProvince','county','year','month','day','individualCount','decimalLongitude'])reject(r,{...o,[term(field)]:'different'});
for(const value of ['0','-1','1.2','NaN','9007199254740992'])reject(r,{...o,[term('individualCount')]:value});
for(const [field,value] of Object.entries({publishingOrgKey:'other',gbifID:'wrong',institutionCode:'other',collectionCode:'other',class:'Mammalia',taxonKey:1,catalogNumber:'wrong',identifier:'wrong',locality:'different',recordedBy:'different','http://unknown.org/status':'rejected',classifications:{bad:{taxonomicStatus:'ACCEPTED',acceptedUsage:{genericName:'Brotogeris',specificEpithet:'chiriri'}}}}))reject({...r,[field]:value});
reject(r,{...o,'http://rs.gbif.org/terms/1.0/gbifID':'other'});
reject(r,{...o,'http://unknown.org/status':'rejected'});
reject(r,o,counties,[]);
reject(r,o,counties,tags.map((t:any)=>t.name==='status'?{...t,created:'2026-01-01T00:00:00Z'}:t));
const county=counties.find((c:any)=>c.countyFips==='06085');
reject(r,o,counties.filter((c:any)=>c!==county));
reject(r,o,[...counties,{...county,countyFips:'06999'}]);
reject(r,o,counties.map((c:any)=>c===county?{...c,status:'retired'}:c));
assert.equal(ebirdOriginalDate({...o,[term('year')]:'2023',[term('month')]:'2',[term('day')]:'29'}),null);
assert.equal(ebirdOriginalDate({...o,[term('year')]:'2024',[term('month')]:'2',[term('day')]:'29'}),'2024-02-29');
const params={mode:EBIRD_MODE,stateCode:'CA',methodReviewPath:'src/data/research/source-method-reviews/ebird-original-fixture.json',methodReviewSha256:'a'.repeat(64),candidatePairs:['06085:brotogeris-versicolurus'],candidateLimit:1};
assert(ebirdParametersSchema.safeParse(params).success);
for(const extra of [{allowAbsence:true},{methodReviewPath:'../outside.json'},{mode:'retained-archive-witnesses'}])assert(!ebirdParametersSchema.safeParse({...params,...extra}).success);
assert.throws(()=>readEbirdArchive({...evaluation.artifact,sha256:'a'.repeat(64)},read));
const bad=gzipSync(Buffer.from(JSON.stringify({schemaVersion:1,files:[{originalPath:'../outside',bytes:1,sha256:sha256('x'),encoding:'base64',contents:Buffer.from('x').toString('base64')}]})));
assert.throws(()=>readEbirdArchive({path:'fixture.gz',bytes:bad.length,sha256:sha256(bad)},()=>bad));
console.log(JSON.stringify({passed:true,retainedOriginalRecords:rows.length,adverseRecords:adverse,explicitCountyWithoutUncertainty:true,atHomeNotAutomaticCaptivity:true,opaqueAnnotationQualifiedWithoutExpertApproval:true,archiveHashAndPathGuards:true}));
