import assert from 'node:assert/strict';
import { parseEpaNrsa1819Csv, epaNrsa1819Date, epaNrsa1819VisitKey, epaNrsa1819VisitIndex, epaNrsa1819PositiveValue as qualify } from '@/lib/research/epa-nrsa-1819-fish-counts';
import { parseEpaNrsaCsv } from '@/lib/research/epa-nrsa-fish-counts';

const body = Buffer.from('UID,note\r\n123,"first\r\nsecond"\r\n456,last\r\n');
const bomBody = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), body]);
const parsed = parseEpaNrsa1819Csv(bomBody, true);
assert.deepEqual(parsed[0].raw, Buffer.from('123,"first\r\nsecond"\r\n'));
assert.equal(parsed[0].physicalEndLineOneBased, 3);
assert.deepEqual(parsed, parseEpaNrsa1819Csv(body, false));
assert.throws(() => parseEpaNrsa1819Csv(bomBody, false), /header BOM/);
assert.throws(() => parseEpaNrsa1819Csv(body, true), /header BOM/);
assert.throws(() => parseEpaNrsaCsv(bomBody), /unexpected CSV BOM/, 'Prior survey parser remains strict');
for (const date of ['', '2/29/2018', '2/30/2019', '13/1/2018', '1/0/2018', '1/1/2023', '2018-01-01']) assert.equal(epaNrsa1819Date(date), null);
assert.equal(epaNrsa1819Date('01/01/2018'), '2018-01-01');
const fish = { UID: '1000339', SITE_ID: 'NRS18_AL_10002', DATE_COL: '7/8/2018', VISIT_NO: '1', STATE: 'AL', TAXA_ID: '143', FINAL_NAME: 'COMMON CARP', IS_DISTINCT: '1', TOTAL: '3', ANOM_CT: '0' };
const sampling = { UID: '2012814', SITE_ID: fish.SITE_ID, DATE_COL: fish.DATE_COL, VISIT_NO: fish.VISIT_NO, STATE: 'AL', SAMPLE_TYPE: 'FISH', FISH_SAMPLING: '', SAMPLED_FISH: 'YES-SUFFICIENT', FISH_SAMPLING_SUFFICIENT: 'Y', ACTUAL_DATE: '' };
const site = { UID: sampling.UID, SITE_ID: fish.SITE_ID, DATE_COL: fish.DATE_COL, VISIT_NO: fish.VISIT_NO, PSTL_CODE: 'AL', STATECTY: 'F01001', CNTYNAME: 'Autauga', EVAL_CAT: 'Target_Sampled', DSGN_CYCLE: '2018-19', YEAR: '2018' };
const taxon = { TAXA_ID: '143', FINAL_NAME: 'COMMON CARP', GENUS: 'CYPRINUS', SPECIES: 'CARPIO' };
const county = { countyFips: '01001', stateCode: 'AL', status: 'active', shortName: 'Autauga', legalName: 'Autauga County', aliases: ['Autauga'] };
const scientific = 'Cyprinus carpio';
assert.equal(qualify(fish, sampling, site, taxon, county, scientific).date, '2018-07-08', 'Different original fish UID is retained when complete identity matches');
assert.equal(qualify({...fish, ANOM_CT: '7'}, sampling, site, taxon, county, scientific).date, '2018-07-08', 'Anomaly count is not an individual-fish ceiling');
for (const effort of ['N', 'NOT_SURE']) assert.equal(qualify(fish, {...sampling, FISH_SAMPLING_SUFFICIENT: effort, SAMPLED_FISH: 'NO-SITE CONDITIONS'}, site, taxon, county, scientific).date, '2018-07-08');
assert.equal(epaNrsa1819VisitKey(fish, 'STATE'), epaNrsa1819VisitKey({...site, DATE_COL: '07/08/2018'}, 'PSTL_CODE'));
assert.deepEqual(epaNrsa1819VisitIndex([{record: sampling}, {record: {...sampling, UID: '999'}}, {record: {...sampling, DATE_COL: ''}}], 'STATE').get(epaNrsa1819VisitKey(fish, 'STATE')!), [0, 1], 'Ambiguous joins remain explicit, never first-row wins');
let adverse = 0;
function invalid(f = fish, s = sampling, g = site, t = taxon, c: typeof county | undefined = county) { assert.equal(qualify(f, s, g, t, c, scientific).date, null); adverse++; }
for (const field of ['SITE_ID', 'DATE_COL', 'VISIT_NO', 'STATE']) invalid({...fish, [field]: 'different'});
for (const field of ['SITE_ID', 'DATE_COL', 'VISIT_NO', 'STATE', 'UID', 'SAMPLE_TYPE']) invalid(fish, {...sampling, [field]: 'different'});
for (const field of ['SITE_ID', 'DATE_COL', 'VISIT_NO', 'PSTL_CODE', 'UID', 'STATECTY', 'CNTYNAME', 'EVAL_CAT', 'DSGN_CYCLE', 'YEAR']) invalid(fish, sampling, {...site, [field]: 'different'});
for (const value of ['0', '-1', '1.1', 'NaN', '9007199254740992']) invalid({...fish, TOTAL: value});
for (const value of ['-1', '1.1', 'NaN']) invalid({...fish, ANOM_CT: value});
for (const flag of ['NO_FISH', 'NO_PERMIT', 'EQUIPMENT_FAILURE', 'NOT_FISHED_REACH_MIN']) invalid(fish, {...sampling, FISH_SAMPLING: flag});
invalid({...fish, IS_DISTINCT: '0'}); invalid({...fish, UID: ''}); invalid(fish, {...sampling, ACTUAL_DATE: '7/9/2018'});
invalid(fish, sampling, site, {...taxon, FINAL_NAME: 'GRASS CARP'}); invalid(fish, sampling, site, {...taxon, TAXA_ID: '999'}); invalid(fish, sampling, site, {...taxon, GENUS: 'OTHER'});
invalid(fish, sampling, site, taxon, {...county, status: 'retired'}); assert.equal(qualify(fish, sampling, site, taxon, undefined, scientific).date, null);
console.log(`EPA NRSA1819 draft parser and predicate tests passed (${adverse} adverse records); no source method or evidence acceptance is implied.`);
import { epaNrsa1819ParametersSchema, EPA_NRSA_SOURCE, EPA_NRSA_ADAPTER, EPA_NRSA_1819_VERSION, EPA_NRSA_1819_MODE } from '@/lib/research/epa-nrsa-1819-fish-counts';
import { isCommittedSnapshotReplayReceipt } from '@/lib/research/validate-run';
const parameters = {mode: EPA_NRSA_1819_MODE, stateCode: 'AR', methodReviewPath: 'src/data/research/source-method-reviews/epa-nrsa-fish-counts-1819-fixture.json', methodReviewSha256: 'a'.repeat(64), candidatePairs: ['05001:cyprinus-carpio'], candidateLimit: 1};
assert(epaNrsa1819ParametersSchema.safeParse(parameters).success);
const receipt = {source_id: EPA_NRSA_SOURCE, adapter_id: EPA_NRSA_ADAPTER, adapter_version: EPA_NRSA_1819_VERSION, parameters};
assert(isCommittedSnapshotReplayReceipt(receipt));
for (const overrides of [{source_id:'other'},{adapter_id:'other'},{adapter_version:'1.0.0'},{parameters:{...parameters,mode:'retained-reviewed-fish-counts'}},{parameters:{...parameters,methodReviewPath:'../outside.json'}},{parameters:{...parameters,methodReviewSha256:'invalid'}}]) assert(!isCommittedSnapshotReplayReceipt({...receipt,...overrides}));
assert(!epaNrsa1819ParametersSchema.safeParse({...parameters,allowAbsence:true}).success);
assert(!epaNrsa1819ParametersSchema.safeParse({...parameters,mode:'retained-reviewed-fish-counts'}).success);
console.log('EPA NRSA1819 parameter/version guards passed.');
