import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseEpaNrsa1314Csv, epaNrsa1314Date, epaNrsa1314Fips, epaNrsa1314PositiveValue as qualify, epaNrsa1314ParametersSchema, EPA_NRSA_1314_MODE, EPA_NRSA_1314_VERSION} from '@/lib/research/epa-nrsa-1314-fish-counts';
import {parseEpaNrsaCsv} from '@/lib/research/epa-nrsa-fish-counts';
import {isCommittedSnapshotReplayReceipt} from '@/lib/research/validate-run';
const raw = Buffer.from('UID,note\r\n123,"Rio Pe\xf1asco\r\nRio Pe\xf1asco"\r\n456,last', 'latin1');
const rows = parseEpaNrsa1314Csv(raw, 'latin1');
assert.deepEqual(rows[0].raw, Buffer.from('123,"Rio Pe\xf1asco\r\nRio Pe\xf1asco"\r\n', 'latin1'));
assert.equal(rows[0].physicalEndLineOneBased, 3); assert.equal(rows[1].physicalEndLineOneBased, 4);
assert.equal(rows[0].record.note, 'Rio Pe\u00f1asco\r\nRio Pe\u00f1asco');
assert.throws(() => parseEpaNrsaCsv(raw));
assert.throws(() => parseEpaNrsa1314Csv(Buffer.from('a,b\r\n1,x\r\n'), 'latin1'));
assert.throws(() => parseEpaNrsa1314Csv(Buffer.from('a,b\r\n1,\xf1\r\n2,\xf1\r\n', 'latin1'), 'latin1'));
assert.throws(() => parseEpaNrsa1314Csv(Buffer.from('a,b\r\n1,\xf1\xe9\r\n', 'latin1'), 'latin1'));
assert.deepEqual(parseEpaNrsa1314Csv(Buffer.from('a,b\r\n1,x\r\n'), 'utf8'), parseEpaNrsaCsv(Buffer.from('a,b\r\n1,x\r\n')));
for (const d of ['2/29/2013','2/30/2014','13/1/2013','1/0/2014','1/1/2018','2013-01-01','']) assert.equal(epaNrsa1314Date(d), null);
assert.equal(epaNrsa1314Date('01/2/2013'), '2013-01-02');
for (const f of ['F05001','5001.0','501','0005001','5.001e3',' 5001']) assert.equal(epaNrsa1314Fips(f), null);
assert.equal(epaNrsa1314Fips('5001'), '05001'); assert.equal(epaNrsa1314Fips('05001'), '05001');
const review=JSON.parse(fs.readFileSync('src/data/research/source-method-reviews/epa-nrsa-fish-counts-1314-20260908-r21-review-a.json','utf8'));
const w=review.witnesses[0], fish=w.fish.sourceFields, site=w.site.sourceFields, taxon=w.taxon.sourceFields;
const registry=JSON.parse(fs.readFileSync('src/data/research/county-equivalent-registry.json','utf8'));
const county=registry.countyEquivalents.find((c:any)=>c.countyFips===w.pairKey.split(':')[0]);
const scientific='Ctenopharyngodon idella'; assert.equal(qualify(fish,site,taxon,county,scientific).date,w.date);
assert.equal(qualify({...fish,ANOM_CT:'999'},site,taxon,county,scientific).date,w.date,'Anomalies need not count distinct fish');
assert.equal(qualify(fish,{...site,STATE:'AR:MS',BORD_RIV:'AR:MS'},taxon,county,scientific).date,w.date);
let adverse=0;const invalid=(f=fish,s=site,t=taxon,c=county)=>{assert.equal(qualify(f,s,t,c,scientific).date,null);adverse++;};
for(const k of ['UID','SITE_ID','DATE_COL','VISIT_NO','PSTL_CODE','SITETYPE','IS_DISTINCT','TAXA_ID','FINAL_NAME'])invalid({...fish,[k]:'different'});
for(const k of ['UID','SITE_ID','DATE_COL','VISIT_NO','PSTL_CODE','SITETYPE','SITESAMP','EVALSTAT','NRS13_EVAL','STUDY','EVALUATED','NRSA_USE','STATECTY','CNTYNAME'])invalid(fish,{...site,[k]:'different'});
for(const n of ['0','-1','1.1','NaN','9007199254740992',''])invalid({...fish,TOTAL:n});
for(const n of ['','-1','1.1','NaN'])invalid({...fish,ANOM_CT:n});
for(const [STATE,BORD_RIV] of [['MS','MS'],['AR:MS','MS:AR'],['AR:AR','AR:AR'],['MO:MS','MO:MS'],['AR:MS:MO','AR:MS:MO']])invalid(fish,{...site,STATE,BORD_RIV});
invalid(fish,site,{...taxon,SPECIES:'other'});invalid(fish,site,taxon,{...county,status:'retired'});assert.equal(qualify(fish,site,taxon,undefined,scientific).date,null);
const parameters={mode:EPA_NRSA_1314_MODE,stateCode:'AR',methodReviewPath:'src/data/research/source-method-reviews/epa-nrsa-fish-counts-1314-fixture.json',methodReviewSha256:'a'.repeat(64),candidatePairs:['05001:cyprinus-carpio'],candidateLimit:1};
assert(epaNrsa1314ParametersSchema.safeParse(parameters).success);
const receipt={source_id:'epa-nrsa-fish-counts',adapter_id:'epa-nrsa-retained-fish-counts',adapter_version:EPA_NRSA_1314_VERSION,parameters};assert(isCommittedSnapshotReplayReceipt(receipt));
for(const overrides of [{adapter_version:'2.0.0'},{source_id:'other'},{parameters:{...parameters,mode:'retained-reviewed-fish-counts-1819'}},{parameters:{...parameters,methodReviewPath:'../outside.json'}}])assert(!isCommittedSnapshotReplayReceipt({...receipt,...overrides}));
assert(!epaNrsa1314ParametersSchema.safeParse({...parameters,allowAbsence:true}).success);
console.log(JSON.stringify({passed:true,adverseRecords:adverse,originalByteParsing:true,modeVersionGuards:true}));
