import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildEbirdResult, ebirdInputPaths, loadEbirdMethod, EBIRD_MODE, EBIRD_SOURCE, EBIRD_ADAPTER, EBIRD_VERSION } from '@/lib/research/ebird-original-observations';
import { isCommittedSnapshotReplayReceipt } from '@/lib/research/validate-run';
import { sha256 } from '@/lib/research/run-files';
const read=(p:string)=>fs.readFileSync(p),mp='src/data/research/source-method-reviews/ebird-original-20260909-r22.json',method=JSON.parse(read(mp).toString()),plan={methodReviewPath:mp,methodReviewSha256:sha256(read(mp))};
const loaded=loadEbirdMethod(plan,read);assert.equal(loaded.rows.length,41);assert.equal(loaded.originals.size,41);assert.equal(loaded.pairReviews.length,5);assert.equal(loaded.method.independentReviews.length,2);
assert(ebirdInputPaths(plan,read).includes('src/lib/research/ebird-original-observations.ts'));
const contexts=['CA','FL'].map(stateCode=>{const p=JSON.parse(read('ops/national-research/plans/ebird-original-20260909-r22/'+stateCode+'.json').toString());assert.equal(p.sourceId,EBIRD_SOURCE);assert(p.candidates.every((candidate:any)=>candidate.sourceId===EBIRD_SOURCE),'Every plan candidate must survive the runner source filter');return {runId:'fixture-ebird-'+stateCode.toLowerCase(),sourceId:EBIRD_SOURCE,stateCode,runStartedAt:new Date(Date.parse(method.reviewedAt)+1000).toISOString(),parameters:{...plan,mode:EBIRD_MODE,stateCode,candidatePairs:p.candidates.map((c:any)=>c.countyFips+':'+c.speciesId),candidateLimit:p.candidates.length},requestedPairs:p.candidates.map((c:any)=>({...c,countyName:'Fixture target label',scientificName:'Brotogeris versicolurus'}))};});
for(const c of contexts){const result=buildEbirdResult(c,read);assert.equal(result.assertions.length,c.requestedPairs.length);assert.equal(result.reviews.length,c.requestedPairs.length);assert.equal(result.outcomes.length,c.requestedPairs.length);assert.equal(result.candidateRecordCount,c.stateCode==='CA'?18:23);assert.equal(result.rejections.length,0);assert.equal(result.upstreamRequests.length,0);assert(result.assertions.every(a=>a.claim_type==='recorded-present'&&a.source_record_date?.startsWith('2024-')&&a.scope==='point'));assert(result.reviews.every(r=>r.review_level==='machine-validated'));assert.deepEqual(buildEbirdResult(c,read),result);}
let rejected=0;const bad=(fn:()=>unknown)=>{assert.throws(fn);rejected++;};
function changedMethod(change:(m:any)=>void){const m=structuredClone(method);change(m);const b=Buffer.from(JSON.stringify(m)),p={...plan,methodReviewSha256:sha256(b)};return ()=>loadEbirdMethod(p,x=>x===mp?b:read(x));}
for(const change of [(m:any)=>{m.sourceId='other';},(m:any)=>{m.sourceYear=2025;},(m:any)=>{m.approvedPairs.pop();},(m:any)=>{m.heldPairs=[m.approvedPairs[0]];},(m:any)=>{m.independentReviews[1]=m.independentReviews[0];},(m:any)=>{m.independentReviews[0].originalCommit='a'.repeat(40);},(m:any)=>{m.acquisitions[0].repositoryBaseCommit='a'.repeat(40);},(m:any)=>{m.acquisitions[4].repositoryBaseCommit='a'.repeat(40);},(m:any)=>{m.acquisitions[0].archive.sha256='a'.repeat(64);},(m:any)=>{m.acquisitions[0].receipt.sha256='a'.repeat(64);},(m:any)=>{m.acquisitions[0].recipe.sha256='a'.repeat(64);},(m:any)=>{m.acquisitions[1].name='search';},(m:any)=>{m.independentReviews[0].actorId='MAIN';},(m:any)=>{m.reviewedAt='2020-01-01T00:00:00Z';}])bad(changedMethod(change));
const c=contexts[0];bad(()=>buildEbirdResult({...c,sourceId:'other'},read));bad(()=>buildEbirdResult({...c,stateCode:'FL'},read));bad(()=>buildEbirdResult({...c,runStartedAt:'2020-01-01T00:00:00Z'},read));bad(()=>buildEbirdResult({...c,requestedPairs:[...c.requestedPairs,c.requestedPairs[0]]},read));bad(()=>buildEbirdResult({...c,requestedPairs:c.requestedPairs.map((p:any)=>({...p,scientificName:'Brotogeris chiriri'}))},read));bad(()=>buildEbirdResult({...c,parameters:{...c.parameters,candidateLimit:1}},read));bad(()=>buildEbirdResult({...c,parameters:{...c.parameters,candidatePairs:['01001:brotogeris-versicolurus']}},read));
const receipt={source_id:EBIRD_SOURCE,adapter_id:EBIRD_ADAPTER,adapter_version:EBIRD_VERSION,parameters:c.parameters};assert(isCommittedSnapshotReplayReceipt(receipt));for(const change of [{adapter_version:'2.0.0'},{source_id:'gbif-preserved-specimens'},{parameters:{...c.parameters,mode:'retained-archive-witnesses'}},{parameters:{...c.parameters,methodReviewPath:'../outside.json'}}])assert(!isCommittedSnapshotReplayReceipt({...receipt,...change}));
console.log(JSON.stringify({passed:true,independentReviewers:2,originalRecords:41,fixturePositiveAssertions:5,realCanonicalRunsCreated:0,rejectedMethodAndScopeMutations:rejected,deterministicReconstruction:true,versionModeAndPathGuards:true}));
